<?php
	if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
	$title = 'Contra Entry';
	$this->headTitle($title);
	?>
	<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($title);?></h1>
	<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('contraentry'));
	$form->prepare();	
	echo $this->form()->openTag($form);
?>
<table width="100%" border="0" cellspacing="1" cellpadding="5" style=" font-family:Tahoma, Geneva, sans-serif;margin:0px auto 0px auto;">
    <tr valign="top">
        <td align="left">
            <table width="100%"  border="0" cellspacing="0" cellpadding="0" align="center">
                <tr valign="top">
                    <td align="left">
                            <div id="showDividend" >
                                <script type="text/javascript">
									$(document).ready(function() {
										$("#BRANCH_ID").focus();
										$('#TRANSACTION_DATE2').datepicker({									
											dateFormat : 'dd-mm-yy'
										});
										$('#chq_date').datepicker({									
											dateFormat : 'dd-M-yy'
										});
										reassignTabOrders();
										bindKeyPress();
										
										var fundCode = $('#COMPANY_ID').val();
										////alert(fundCode);
										if(fundCode != '') {
											var frm = 'c';
											//$.post('/contraentry/getSuggestCOAPaymentRceipt',{'frm' : frm, 'fundCode' : fundCode}, function(data) {
											$.getJSON('/contraentry/getSuggestCOAPaymentRceipt',{frm : frm, fundCode : fundCode}, function(data) {
												if(data.length >0) {
													////alert(data);
													suggestionData.coaCodes = JSON.stringify(data);
													reassignTabOrders();
												} else {
													suggestionData = {};
												}
											});
										}
										
									});
									
									var suggestionData = {};
									suggestionData.coaCodes = {};
									function doValidationContraEntry() {
                                       var formObject = document.contraentry;
                                       if(formObject.BRANCH_ID.value=="") {
                                            //alert("Please Select Branch!");
                                            formObject.BRANCH_ID.focus();
                                            return false;
                                        }
                                        if(formObject.TRANSACTION_DATE2.value=="") {
                                            //alert("Please Enter Transection Record Date!");
                                            formObject.TRANSACTION_DATE2.focus();
                                            return false;
                                        }
										
										/*if($('#chequeNo').length > 0) {
											if(formObject.chequeNo.value=="") {
												//alert("Please Enter Cheque No!");
												formObject.chequeNo.focus();
												return false;
											}
										}
										
										if($('#chq_date').length > 0) {
											if(formObject.chq_date.value=="") {
												//alert("Please Enter Cheque Date!");
												formObject.chq_date.focus();
												return false;
											}
										}*/
										
										if(document.getElementById('coa_head'+1).value=="") {
											//alert("Please Enter COA-Head!");
											document.getElementById('coa_head'+1).focus();
											return false;
                                        }
										if(typeof($('input[name=VOUCHER_TYPE1]:radio:checked').val()) == 'undefined') {
											//alert("Please Select DR/CR!");
											document.getElementById('VOUCHER_TYPEDebit'+1).focus();
											return false;	
										}
                                        if(document.getElementById('PAYMENT_AMOUNT'+1).value=="0.00") {
                                                //alert("Please Enter Amount!");
                                                document.getElementById('PAYMENT_AMOUNT'+1).focus();
                                                return false;
                                        }								
                                        var numOfRows = $("#NUMBER_OF_ROWS").val();
										for(var i = 2; i < numOfRows; i++ ) {
											if(document.getElementById('coa_head'+i).value !="") {
												if(typeof($('input[name=VOUCHER_TYPE'+i+']:radio:checked').val()) == 'undefined') {
													//alert("Please Select DR/CR!");
													document.getElementById('VOUCHER_TYPEDebit'+i).focus();
													return false;	
												}
												if(document.getElementById('PAYMENT_AMOUNT'+i).value=="0.00") {
													//alert("Please Enter Amount!");
													document.getElementById('PAYMENT_AMOUNT'+i).focus();
													return false;
												}
											}
										}
										
                                        var Totaldebit 	= 0;
										var TotalCredit = 0;
										Totaldebit 		= $('#totalDrAmount').val();
										Totaldebit 		= Number(Totaldebit.replace(/\,/g,""));
										
										TotalCredit 	= $('#totalCrAmount').val();
										TotalCredit 	= Number(TotalCredit.replace(/\,/g,""));

										Totaldebit = Totaldebit.toFixed(2);
										TotalCredit = TotalCredit.toFixed(2);			

										if(Number(Totaldebit) != Number(TotalCredit)){
											if(Totaldebit > TotalCredit) {
												var diffAmount = Totaldebit - TotalCredit;	
											} else {
												var diffAmount = TotalCredit - Totaldebit;
											}
											//alert("Debit and Credit Amount mismatch! Difference : " + numberFormat('',diffAmount,2,',','.'));
											document.getElementById('PAYMENT_AMOUNT'+2).focus();
											return false;
										}
										if(!confirm('Are you sure, you want to proceed?')){
                                            return false;
                                        }
                                        return true;
                                    }
									
                                    function blankAllFields() {
										var numOfRows = $("#NUMBER_OF_ROWS").val();
                                        for(var i = 1; i< numOfRows; i++) {
                                            $('#coa_head'+i).attr('value','');
											$('#COA_CODEshow'+i).html('');
											$('#COA_CODE'+i).attr('value','');
											$('#PAYMENT_AMOUNT'+i).attr('value','0.00');
                                        }
										$('#PARTICULARS').attr('value','');
										var fundCode = $('#COMPANY_ID').val();
										////alert(fundCode);
										if(fundCode != '') {
											var frm = 'c';
											//$.post('/contraentry/getSuggestCOAPaymentRceipt',{'frm' : frm, 'fundCode' : fundCode}, function(data) {
											$.getJSON('/contraentry/getSuggestCOAPaymentRceipt',{frm : frm, fundCode : fundCode}, function(data) {
												if(data.length >0) {
													////alert(data);
													suggestionData.coaCodes = JSON.stringify(data);
													reassignTabOrders();
												} else {
													suggestionData = {};
												}
											});
										}
                                    }    
									
									function AddTabRow() {
										var numOfRows 	= $("#NUMBER_OF_ROWS").val();
										var numOfRowsId = numOfRows - 1;
										var coaCode 	= $("#COA_CODE"+numOfRowsId).val();
										var PAYMENT_AMOUNT		= $("#PAYMENT_AMOUNT"+numOfRowsId).val();
										PAYMENT_AMOUNT			= Number(PAYMENT_AMOUNT.replace(/[^\d\.\-\ ]/g, ''));
										coaCode 		= coaCode.substr(0,3);
										
										if(PAYMENT_AMOUNT == 0) {
												return false;
										} else {
											// clone the last row in the table
											var $tr = '';//$("#ClosingBalTab").find("tbody tr:last").clone();
											
											if((coaCode == 303) || (coaCode == 304)) {
												////alert(coaCode);
												$tr = $("#ClosingBalTab").find("#transDetails"+numOfRowsId).prev('tr').clone();
												
												//$('#maintable tbody>tr:last').prev('tr')
											} else {
												$tr = $("#ClosingBalTab").find("tbody tr:last").clone();
											}
											
											$tr.find("#coa_head"+numOfRowsId).attr("name", function() {
												// break the field name and it's number into two parts
												var parts = this.name.match(/(\D+)(\d+)$/);
												// create a unique name for the new field by incrementing
												// the number for the previous field by 1
												return parts[1] + ++parts[2];
											// repeat for id attributes
											}).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											}).attr("value", function(){
												return "";
											});
											
											$tr.find("#COA_CODEshow"+numOfRowsId).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											});
											
											$tr.find("#COA_CODE"+numOfRowsId).attr("name", function() {
												// break the field name and it's number into two parts
												var parts = this.name.match(/(\D+)(\d+)$/);
												// create a unique name for the new field by incrementing
												// the number for the previous field by 1
												return parts[1] + ++parts[2];
											// repeat for id attributes
											}).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											}).attr("value", function(){
												return "";
											}).attr("checked", function(){
												return false;
											});
											
											$tr.find("#VOUCHER_TYPEDebit"+numOfRowsId).attr("name", function() {
												// break the field name and it's number into two parts
												var parts = this.name.match(/(\D+)(\d+)$/);
												// create a unique name for the new field by incrementing
												// the number for the previous field by 1
												return parts[1] + ++parts[2];
											// repeat for id attributes
											}).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											}).attr("value", function(){
												return "D";
											}).attr("checked", function(){
												return false;
											}).attr("onClick", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return "DrCrAmountAlign("+ parts[2] +");totalDRCRShow();";
											});
											
											$tr.find("#VOUCHER_TYPECredit"+numOfRowsId).attr("name", function() {
												// break the field name and it's number into two parts
												var parts = this.name.match(/(\D+)(\d+)$/);
												// create a unique name for the new field by incrementing
												// the number for the previous field by 1
												return parts[1] + ++parts[2];
											// repeat for id attributes
											}).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											}).attr("value", function(){
												return "C";
											}).attr("checked", function(){
												return false;
											}).attr("onClick", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return "DrCrAmountAlign("+ parts[2] +");totalDRCRShow();";
											});
											
											$tr.find("#PAYMENT_AMOUNT"+numOfRowsId).attr("name", function() {
												// break the field name and it's number into two parts
												var parts = this.name.match(/(\D+)(\d+)$/);
												// create a unique name for the new field by incrementing
												// the number for the previous field by 1
												return parts[1] + ++parts[2];
											// repeat for id attributes
											}).attr("id", function(){
												var parts = this.id.match(/(\D+)(\d+)$/);
												return parts[1] + ++parts[2];
											}).attr("onBlur", function(){
												return "numberFormat(\"PAYMENT_AMOUNT"+numOfRows+"\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\"; AddTabRow();totalDRCRShow();";
											}).attr("value", function(){
												return "0.00";
											});
											
											$("#ClosingBalTab").find("tbody tr:last").after($tr);
											$("#COA_CODEshow"+numOfRows).html('');
											$("#NUMBER_OF_ROWS").attr("value",Number(numOfRows)+1);
											reassignTabOrders();
											bindKeyPress();
										}
									}
									
									function addRemoveTransDetails(coaCode,id) {
										coaCode = coaCode.substr(0,3);
										if((coaCode == 303) || (coaCode == 304)) {
											//$("#ClosingBalTab").find("tbody tr:gt(2)").remove();
											//$("#NUMBER_OF_ROWS").attr("value",2);
											var tranDetails = '';
											if(coaCode == 303) {
												if($('#transDetails'+id).length > 0) {
													$('#transDetails'+id).html('');
													$('#transDetails'+id).html('<td colspan="4">Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn" style="width:150px;" type="text"/></td>');
												} else {
													tranDetails = '<tr id="transDetails'+id+'"><td colspan="4"><div style="position:relative; display:block;" id="showCustBankName">Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text" onkeyup="bankNameSuggestForCashInHand(this.value,this.id);"/><div id="BankNameSuggestionsCIH" style="display:none; width:205px; height:205px;" class="ClassempIdSuggestions"><div id="BankNameSuggestionsListCIH" class="ClasssuggestingEmpIdList"></div></div></div></td></tr>';
												}
												
											} else {
												if($('#transDetails'+id).length > 0) {
													$('#transDetails'+id).html('');
													$('#transDetails'+id).html('<td colspan="4">Instrument No. : <input maxlength="20" class="FormNumericTypeInput" type="text"  id="chequeNo" name="chequeNo" style="text-align:left;" value=""/>&nbsp;&nbsp;&nbsp;Date : <input name="chq_date" class="FormDateTypeInput" id="chq_date'+id+'" type="text"  onclick="showCalender(\'chq_date\''+id+',\'chq_date\''+id+')"/>&nbsp;&nbsp;&nbsp;Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn" style="width:150px;" type="text"/></td>');
												} else {
													tranDetails = '<tr id="transDetails'+id+'"><td colspan="4"><div style="position:relative; display:block;" id="showCustBankName">Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text" autocomplete="off" onkeyup="bankNameSuggestForCashAtBank(this.value,this.id);"/><div id="BankNameSuggestions" style="display:none; width:205px; height:205px;" class="ClassempIdSuggestions"><div id="BankNameSuggestionsList" class="ClasssuggestingEmpIdList"></div></div>&nbsp;&nbsp;Instrument No. : <input maxlength="20" class="FormNumericTypeInput" type="text"  id="chequeNo" name="chequeNo" style="text-align:left;" value=""/>&nbsp;&nbsp;&nbsp;Date : <input name="chq_date" class="FormDateTypeInput" id="chq_date'+id+'" type="text" onclick="showCalender(\'chq_date\''+id+',\'chq_date\''+id+')"/>&nbsp;&nbsp;&nbsp;</div></td></tr>';
												}
											}
											$("#ClosingBalTab").find("tbody tr:last").after(tranDetails);
											reassignTabOrders();
											bindKeyPress();
										} else {
											if($('#transDetails'+id).length > 0) {
												$('#transDetails'+id).remove();
												reassignTabOrders();
												bindKeyPress();
											}
										}
										$(document).ready(function(){
												$('#chq_date'+id).datepicker({									
													dateFormat : 'dd-mm-yy'
												});
										});
									}
									function bankNameSuggestForCashAtBank(inputString,id) {
										if(inputString.length == 0)
										{
											$('#BankNameSuggestions'+id).fadeOut();
										} 
										else 
										{
											$.post("/contraentry/getSuggestBankName", {queryString: inputString,id: id}, 
											//$.getJSON("/contraentry/getSuggestBankName",{queryString: inputString,},
											function(j)
											{
												if(j.length >0) 
												{
													////alert(j);
													//document.getElementById('BankNameSuggestionsList'+id).html(j);
													//document.getElementById('BankNameSuggestions'+id).fadeIn("slow");
													$('#BankNameSuggestionsList').html(j);
													$('#BankNameSuggestions').fadeIn("slow");
													
												} else{
													$('#BankNameSuggestions').fadeOut();
												}
											});
										}
									}
									function fill_bank_name(thisValue,id){
									   if(thisValue == ''){
											document.getElementById(id).value = '';
											return false;
										}
										document.getElementById(id).value = thisValue;
										$('#BankNameSuggestions').fadeOut();
									}
									function bankNameSuggestForCashInHand(inputString,id) {
										if(inputString.length == 0)
										{
											$('#BankNameSuggestionsCIH').fadeOut();
										} 
										else 
										{
											$.post("/contraentry/getSuggestBankNameForCIH", {queryString: inputString,id: id}, 
											//$.getJSON("/contraentry/getSuggestBankNameForCIH",{queryString: inputString,},
											function(j)
											{
												if(j.length >0) 
												{
													////alert(j);
													//document.getElementById('BankNameSuggestionsList'+id).html(j);
													//document.getElementById('BankNameSuggestions'+id).fadeIn("slow");
													$('#BankNameSuggestionsListCIH').html(j);
													$('#BankNameSuggestionsCIH').fadeIn("slow");
													
												} else{
													$('#BankNameSuggestionsCIH').fadeOut();
												}
											});
										}
									}
									function fill_bank_nameCIH(thisValue,id){
									   if(thisValue == ''){
											document.getElementById(id).value = '';
											return false;
										}
										document.getElementById(id).value = thisValue;
										$('#BankNameSuggestionsCIH').fadeOut();
									}	
									function callback(item,no) {
										var coaCodeHead = item.text;
										var coaCode		= item.id
										
										$('#coa_head'+no).attr('value',coaCodeHead);
										$('#COA_CODEshow'+no).html(coaCode);
										$('#COA_CODE'+no).attr('value',coaCode);
									   
										var frm      = 'c';
										var fundCode = $('#BRANCH_ID').val();
										$.post('/contraentry/getTrialBalPayRecAmount',{coaCode: coaCode, frm : frm, fundCode : fundCode }, function(data) {
										//$.getJSON('/contraentry/getTrialBalPayRecAmount',{coaCode: coaCode, frm : frm, fundCode : fundCode }, function(data) {							
												document.getElementById('PAYMENT_AMOUNT'+no).value = data;
											});
										addRemoveTransDetails(coaCode,no);
										return false;
									}
									
									/*function doValidationContraEntry() {
										return true;
									}*/
									
									function bindKeyPress() {
										$('#contraentry input,select,textarea').unbind("keypress");
										$('#contraentry input,select,textarea').bind('keypress',function (event){
											var currentElementId = $(this).attr('id');
											var tabindex = Number($('#'+currentElementId).attr('tabindex'));
											var parts = (currentElementId.match(/(\D+)(\d+)$/) != null) ? currentElementId.match(/(\D+)(\d+)$/) : '';
											if (event.keyCode === 13) {
												if(currentElementId == 'insertContra') {
													if(doValidationContraEntry()) {
														return true;
													} else {
														return false;
													}
													return false;
													
												} else {
													var newTabIndex = tabindex + 1;
													if(parts[1] == 'coa_head') {
														//var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
														//$('#'+nextElementId).focus();
														//return true;
														////alert('helllllllllllll');
													} else if(parts[1] == 'PAYMENT_AMOUNT') {
														$('#'+currentElementId).trigger('blur');
														var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
														$('#'+nextElementId).focus();
													} else {
														var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
														if($('#'+nextElementId).attr('type') == 'radio') {
															$('#'+nextElementId).trigger('click');
															$('#'+nextElementId).focus();
														} else {
															$('#'+nextElementId).focus();
														}
													}
													return false;
												}
											} else {
												return true;
											}
										});
									}
									
									function reassignTabOrders() {
										var tabindex = 1;
										$('.jsonSuggestResults').remove();
										
										$('#contraentry input,select,textarea').each(function() {
											var $input = $(this);
											if ($input.is(':visible')) {
												$input.attr("tabindex", tabindex);
												var coaElementId = $('[tabindex=' + tabindex + ']').attr('id');
												var parts = (coaElementId.match(/(\D+)(\d+)$/) != null) ? coaElementId.match(/(\D+)(\d+)$/) : '';
												
												if($.isArray(parts)){
													if(parts[1] == 'coa_head') {
														$('input#coa_head'+parts[2]).unbind("keyup");
														$('input#coa_head'+parts[2]).unbind("blur");
														$('input#coa_head'+parts[2]).unbind("focus");
														$('input#coa_head'+parts[2]).jsonSuggest(suggestionData.coaCodes, {defaultId:parts[2],onSelect:callback});
													}
												}
												tabindex++;
											}
										});
									}
									
									function DrCrAmountAlign(e){
										/*var coaCode = $("#COA_CODE"+e).val();
										if(coaCode.substr(0,1) == 3 ){
											document.getElementById('VOUCHER_TYPEDebit'+e).checked = true;
										} else if(coaCode.substr(0,1) == 1){
											document.getElementById('VOUCHER_TYPECredit'+e).checked = true;
										} else if(coaCode.substr(0,1) == 5){
											document.getElementById('VOUCHER_TYPECredit'+e).checked = true;
										} else if(coaCode.substr(0,1) == 6){
											document.getElementById('VOUCHER_TYPEDebit'+e).checked = true;
										} else if(coaCode.substr(0,1) == 2){
											document.getElementById('VOUCHER_TYPECredit'+e).checked = true;
										} else {
											document.getElementById('VOUCHER_TYPEDebit'+e).checked = true;
										}*/
										if(document.getElementById('VOUCHER_TYPEDebit'+e).checked==true){	
											document.getElementById('PAYMENT_AMOUNT'+e).style.textAlign = 'left'
											
										}
										if(document.getElementById('VOUCHER_TYPECredit'+e).checked==true){
											document.getElementById('PAYMENT_AMOUNT'+e).style.textAlign = 'right'
										}
										return true;
									}
									
									function totalDRCRShow() {
										var numOfRows = $("#NUMBER_OF_ROWS").val();
										var k=0;
										var i=0;
										var Totaldebit = 0;
										var TotalCredit = 0;
										for(i = 1; i < numOfRows; i++){
											if((document.getElementById('VOUCHER_TYPEDebit'+i).checked==true) || (document.getElementById('VOUCHER_TYPECredit'+i).checked==true)){
												if((document.getElementById('VOUCHER_TYPEDebit'+i).checked==true) && (document.getElementById('PAYMENT_AMOUNT'+i).value !="")){
													var debitAmount 	= $('#PAYMENT_AMOUNT'+i).val();
													debitAmount 		= Number(debitAmount.replace(/\,/g,""));
													Totaldebit      	= Totaldebit + debitAmount;
												}if((document.getElementById('VOUCHER_TYPECredit'+i).checked==true) && (document.getElementById('PAYMENT_AMOUNT'+i).value !="")){
													var creditAmount 	= $('#PAYMENT_AMOUNT'+i).val();
													creditAmount 		= Number(creditAmount.replace(/\,/g,""));
													TotalCredit 		= TotalCredit + creditAmount;
												}								
											}
										}
										$("#DRTOTAL").html(numberFormat('',Totaldebit,2,',','.'));
										$("#CRTOTAL").html(numberFormat('',TotalCredit,2,',','.'));
										
										$("#totalDrAmount").attr('value',Totaldebit);
										$("#totalCrAmount").attr('value',TotalCredit);
									}
									function checkCalender(thisDate,businessDate){
										var fromDate = thisDate;
										var toDate = businessDate;
										var hiddenBusinessDate = document.getElementById('HIDDEN_BUSINESS_DATE').value;
										if((fromDate != '') && (toDate != '')){							
											var tempFromDate = fromDate.split('-');
											var tempToDate = toDate.split('-');
											var tempHBD = hiddenBusinessDate.split('-');
											var a = tempFromDate[1]+'/'+tempFromDate[0]+'/'+tempFromDate[2];
											var b = tempToDate[1]+'/'+tempToDate[0]+'/'+tempToDate[2];
											var c = tempHBD[1]+'/'+tempHBD[0]+'/'+tempHBD[2];
											if ((dates.compare(c,a) == 1)) {
												//alert('Company Business Starting Date is ' + hiddenBusinessDate + '! \nPlease select greater than date: ' + hiddenBusinessDate);
												$("#TRANSACTION_DATE2").attr("value",businessDate);
												return false;
											} else if ((dates.compare(b,a) == 1) || (dates.compare(b,a) == 0)) {
												return true;
											}else {
												//alert('Please select less than or equal to business date!');
												$("#TRANSACTION_DATE2").attr("value",businessDate);
												//$("#tranDateTo").attr("value",businessDate);
												return false;
											}
										}
									}
                                    </script>
                                         <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
												<legend style='border:0px;'>Contra Entry</legend>
                                                <table  width="100%" border="0" cellpadding="3" cellspacing="0">
                                                    <tr>
                                                        <td>
                                                            <table width="100%" border="0" cellpadding="3" cellspacing="0" style="margin:0px auto 0px auto;font-size:100%;">	
                                                                <tr valign="top">
                                                                  <td width="100%" colspan="4" align="center">
                                                                        <table width="70%" border="0" cellpadding="3" cellspacing="0" style="margin:0px auto 0px auto;font-size:85%;font-family:Tahoma, Geneva, sans-serif;">
                                                                                <tr>                                    
                                                                                    <td>Company</td>
                                                                                    <td> : </td>
                                                                                    <td>
                                                                                         <input type="hidden" name="COMPANY_ID"  id="COMPANY_ID" value="1" />
																						<?php //echo $this->formRow($form->get('BRANCH_ID')); ?>
                                                                                        <select name="BRANCH_ID" id="BRANCH_ID" onchange="blankAllFields();" style="padding-left:10px;font-family:Tahoma, Geneva, sans-serif;font-size:100%;">
                                                                                        <option value="">~~ Please Choose ~~</option>
                                                                                        <option value="1" selected="selected">Head Office</option>
                                                                                    </select>
                                                                                    </td>
                                                                                    <td>&nbsp;</td>
                                                                                </tr>
                                                                                <tr>                                    
                                                                                    <td>Transaction Date</td>
                                                                                    <td> : </td>
                                                                                    <td>
                                                                                    <?php echo $this->formRow($form->get('HIDDEN_BUSINESS_DATE')); ?>
																					<?php echo $this->formRow($form->get('TRANSACTION_DATE')); ?>
                                                                                    <input type="hidden" name="EFFECTED_AT_BANK" value="n"/>
                                                                                    <input type="hidden" name="AUTO_TRANSACTION" value="n"/>
                                                                                    </td>
                                                                                    <td>&nbsp;</td>
                                                                                </tr>
                                                                        </table>
                                                                  </td>
                                                              </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                     <tr valign="top" >
                                                            <td align="center">
                                                                    <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
																	<legend style=" border:0px;cursor:pointer;" onClick="return ShowHide('viewcomp_minorest')">COA Record</legend>
                                                                   	<table id="ClosingBalTab" border="0" width="100%" align="center" cellspacing="1" cellpadding="3" style="font-size:85%;">
                                                                               <?php
                                                                               	$tableTR = '';
																				/*$tableTR .='<tr valign="top" style="font-weight:bold;">
																								<td width="21%" align="right" class="" colspan="4">';
																				$tableTR .= '<a href="#" onclick="Popup=window.open(\'../coa/add\',\'Popup\',\'width=900,height=600,left=280,top=80,toolbar=no\')">Add New COA</a></td></tr>';*/	
																				$tableTR .='<tr valign="top" style="font-weight:bold; text-align:center; background:#E8E1E1;">
																								<td width="50%" align="left" class="">ACCOUNT HEAD</td>
																								<td width="20%" align="center" class="">ACCOUNT CODE</td>
																								<td width="15%" align="center" class="">DR/CR</td>
																								<td width="15%" align="right" class="">AMOUNT</td>
																							</tr>';
																				for($i=1; $i<=1; $i++){
																					$tableTR .="<tr valign='top' >
																								<td align='left' class=''>
																										<input style='width:320px;' name='coa_head{$i}' type='text' id='coa_head{$i}' value='' autocomplete='off' onclick='if($(\"#BRANCH_ID\").val()==\"\"){ //alert(\"Please select branch!\");  $(\"#BRANCH_ID\").focus();}' />
																								</td>
																								<td align='center' class=''><div id='COA_CODEshow{$i}'></div><input type='hidden' readonly='readonly' style='background-color:#999;font-family:Tahoma, Geneva, sans-serif;' name='COA_CODE{$i}' id='COA_CODE{$i}' size='20'/></td>
																								<td  align='center' class=''>
																									<input type='radio' onclick='DrCrAmountAlign($i); totalDRCRShow();' name='VOUCHER_TYPE{$i}' id='VOUCHER_TYPEDebit{$i}' value='D'/>Dr
																									<input type='radio' onclick='DrCrAmountAlign($i); totalDRCRShow();' name='VOUCHER_TYPE{$i}' id='VOUCHER_TYPECredit{$i}' value='C'/>Cr
																								</td>
																								<td align='left' class=''><input type='text' name='PAYMENT_AMOUNT{$i}' id='PAYMENT_AMOUNT{$i}' onkeyup='removeChar(this);' size='15' style='text-align:right;font-family:Tahoma, Geneva, sans-serif;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"PAYMENT_AMOUNT{$i}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\"; AddTabRow(); totalDRCRShow();' value=\"0.00\" /></td>
																							</tr>";	
																				}
																				echo $tableTR;
																			   ?>
                                                                           </table>
                                                                           <table border="0" width="100%" align="center" cellspacing="1" cellpadding="3" style="font-size:85%;background:#E8E1E1;font-family:Tahoma, Geneva, sans-serif;">
                                                                      		<tr valign='top' style="font-weight:bold;background:#E8E1E1;">                                                                                <td width="75%" colspan="3" align='right'>&nbsp;</td>
                                                                                <td width="25%" align='left'>______________</td>
                                                                           </tr>
                                                                           <tr valign='top' style="font-weight:bold;background:#E8E1E1;">                                                                                <td width="75%" colspan="3"  align='right' class=''>Total Debit : </td>
                                                                                <td width="25%" align='left'><span id="DRTOTAL">0.00</span></td>
                                                                           </tr>
                                                                           <tr valign='top' style="font-weight:bold;background:#E8E1E1;">                                                                                <td width="75%" colspan="3"  align='right' class=''>&nbsp;</td>
                                                                                <td width="25%" align='right' class=''>______________</td>
                                                                           </tr>
                                                                           <tr valign='top' style="font-weight:bold;" >
                                                                                <td  width="75%" colspan="3" align='right'>Total Credit : </td>
                                                                                <td  width="25%" align='right'><span id="CRTOTAL">0.00</span></td>
                                                                           </tr>
                                                                           <tr valign='top' >
                                                                                <td  align='left' valign='top' class='' colspan='5'>
                                                                                    <table width='100%' border='0' cellspacing='2' cellpadding='2'>
                                                                                       <tr valign='top'  style='font-weight:bold; text-align:center;' >
                                                                                            <td width='13%' align='left' class=''>Particular</td>
                                                                                            <td width='1%' align='left' class=''> : </td>
                                                                                            <td width='86%' align='center' class=''><textarea style="width:600px;font-family:Tahoma, Geneva, sans-serif;" rows="3" cols="100" name='PARTICULARS' id='PARTICULARS'></textarea></td>
                                                                                        </tr>
                                                                                    </table>
                                                                                </td>
                                                                            </tr>
                                                                            <tr valign="top">
                                                                                 <td align="center" colspan="5">
                                                                                 <input type="hidden" name="totalDrAmount" id="totalDrAmount" value="0" />
                                                                                 <input type="hidden" name="totalCrAmount" id="totalCrAmount" value="0"/>
                                            									 <input type="hidden" name="NUMBER_OF_ROWS" id="NUMBER_OF_ROWS" value="<?php echo $i; ?>"/>
                                            									 <?php echo $this->formRow($form->get('submit')); ?>
                                                                                </td>
                                                                             </tr>
                                                                           </table>                                                                      
                                                                </fieldset>
                                                              
                                                            </td>
                                                  </tr>
                                                </table>
                                        </fieldset>
                            </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
           
    </table>
<?php 
//echo $this->formCollection($form);
echo $this->form()->closeTag();
?>