<?php
	$title = 'Edit SR and Zone Map';
	$this->headTitle($title);
?>
 <script type="text/javascript">
	$(document).ready(function(){
			$("#DESIGNATION_ID").focus();
		});
	 function doValidationSrZoneMapForm() {
		if(document.getElementById('DESIGNATION_ID').value=="") {
			//alert("Please select Designation!");
			document.getElementById('DESIGNATION_ID').focus();
			return false;
		}
		if(document.getElementById('EMPLOYEE_ID').value=="") {
			//alert("Please select SR name!");
			document.getElementById('EMPLOYEE_ID').focus();
			return false;
		}
		/*if(document.getElementById('ZONE_ID').value=="") {
			alert("Please select Zone name!");
			document.getElementById('ZONE_ID').focus();
			return false;
		}*/
		if(!confirm('Are you sure, you want to proceed?')){
			return false;
		}
		return true;
	}
	function getEmployeeName(designationId) {
		//alert(designationId);
		//$.post('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
		$.getJSON('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
				//alert(j);
				if(j.length>0)
				{
					var options = '';
					options += '<option value="">Select Emp. Name</option>';
					for (var i = 0; i < j.length; i++) {
					options += '<option value="' + j[i].optionValue + '">' + j[i].optionDisplay + '</option>';
					}
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
				else
				{
					options = '<option value="">Select Emp. Name</option>';
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
			});
	}
 </script>
<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url(
		'srzonemap',
		array(
			'action'	=> 'edit',
			'id'		=> $this->id,
		)));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('SR_ZONE_MAP_ID'));
?>
<table width="70%" class="frmTbl" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
        <tr valign="top">
            <td colspan="4" align="center"><h1><?php echo $this->escapeHtml($title);?></h1></td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">Designation</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('DESIGNATION_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">SR NAME</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('EMPLOYEE_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">ZONE NAME</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('ZONE_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
       
     
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right"></td>
            <td align="left"></td>
            <td align="left"></td>
        </tr>
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right">&nbsp;</td>
            <td align="left">&nbsp;</td>
            <td align="left">
				<?php echo $this->formSubmit($form->get('submit'));?>
                <input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type="reset"  name="Reset" value="Reset" />
            </td>
        </tr>
    </table>
<?php
	echo $this->form()->closeTag();
?>
<script>
$('form#srZoneMap input, select, textarea, button').keydown(function (e) {
			if (e.keyCode == 13) {
				var inputs = $(this).parents("form").eq(0).find(":input, select, textarea, button");
				if (inputs[inputs.index(this) + 1] != null) {                    
					inputs[inputs.index(this) + 1].focus();
					
				}else{
					doValidationSupplierInformationForm();
				}
				
				e.preventDefault();
				return false;
			}
		});
</script>