<?php if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
?>
<p style="font-family:Tahoma, Geneva, sans-serif;">
	<a href="<?php echo $this->url('srzonemap', array('action'=>'add'));?>">Add SR Aand Zone Map</a> &nbsp;
</p>
<?php
	$coaTitle = 'SR and Zone Map';
	$this->headTitle($coaTitle);
?>
<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($coaTitle); ?></h1>
<table class="table" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
    <tr>
        <th>SL#</th>
        <th>SR NAME</th>
        <th>ZONE NAME</th>
        <th>START DATE</th>
        <th>END DATE</th>
        <th>BUSINESS DATE</th>
        <!--<th>&nbsp;</th>-->
    </tr>
    <?php 
	$class = '';
	$i = 1; 
	foreach ($srZoneMaps as $srZoneMap) : 
	if($class == 'evenRow') {
		$class = 'oddRow';
	} else {
		$class = 'evenRow';
	}
	?>
    <tr class="<?php echo $class; ?>">
        <td><?php echo $i;?></td>
        <td><?php echo $this->escapeHtml($srZoneMap->EMPLOYEE_NAME);?></td>
        <td><?php echo $this->escapeHtml($srZoneMap->NAME);?></td>
        <td><?php echo $this->escapeHtml($srZoneMap->START_DATE);?></td>
        <td><?php echo $this->escapeHtml($srZoneMap->END_DATE);?></td>
        <td><?php echo $this->escapeHtml($srZoneMap->BUSINESS_DATE);?></td>
        <!--<td>
            <a href="<?php // echo $this->url('srzonemap',array('action'=>'edit', 'id' => $srZoneMap->SR_ZONE_MAP_ID));?>">Edit</a>
            
        </td>-->
    </tr>
    <?php $i++; endforeach; ?>
</table>
<span style="font-family:Tahoma, Geneva, sans-serif;font-size:85%;">
<?php 
	//echo $this->paginationControl($srZoneMaps,'sliding',array('partial/paginator.phtml', 'ZoneInformation'),array('route' => 'srzonemap'));
?>
</span>