<?php
	$title = 'Edit Zone Information';
	$this->headTitle($title);
?>
     <script type="text/javascript">
	 	$(document).ready(function(){
			$("#NAME").focus();
		});	
	 function doValidationZoneInformationForm() {
		if(document.getElementById('NAME').value=="") {
			//alert("Please input name!");
			document.getElementById('NAME').focus();
			return false;
		}
		if(document.getElementById('SHORT_NAME').value=="") {
			//alert("Please input short name!");
			document.getElementById('SHORT_NAME').focus();
			return false;
		}
		if(document.getElementById('ADDRESS').value=="") {
			//alert("Please input address!");
			document.getElementById('ADDRESS').focus();
			return false;
		}
		if(!confirm('Are you sure, you want to proceed?')){
			return false;
		}
		return true;
	}
	 
	 
	</script>
<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url(
		'zoneinformation',
		array(
			'action'	=> 'edit',
			'id'		=> $this->id,
		)));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('ZONE_ID'));
?>
<table width="70%" class="frmTbl" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
        <tr valign="top">
            <td colspan="4" align="center"><h1><?php echo $this->escapeHtml($title);?></h1></td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">NAME</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('NAME')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">SHORT NAME</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('SHORT_NAME')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right">ADDRESS</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('ADDRESS')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
     
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right"></td>
            <td align="left"></td>
            <td align="left"></td>
        </tr>
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right">&nbsp;</td>
            <td align="left">&nbsp;</td>
            <td align="left">
				<?php echo $this->formSubmit($form->get('submit'));?>
              
            </td>
        </tr>
    </table>
<?php
	echo $this->form()->closeTag();
?>
<script>
$('form#zoneInformation input, select, textarea, button').keydown(function (e) {
			if (e.keyCode == 13) {
				var inputs = $(this).parents("form").eq(0).find(":input, select, textarea, button");
				if (inputs[inputs.index(this) + 1] != null) {                    
					inputs[inputs.index(this) + 1].focus();
					
				}else{
					doValidationZoneInformationForm();
				}
				
				e.preventDefault();
				return false;
			}
		});
</script>