<?php
	$title = 'Sales Representaive Stock Report';
	$this->headTitle($title);
	?> 
	<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($title);?></h1>
	<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('srstockreport'));
	$form->prepare();	
	echo $this->form()->openTag($form);
	?>
     <table width="95%" border="0" cellspacing="1" cellpadding="10" style="font-family:Tahoma, Geneva, sans-serif;margin:0px auto 0px auto; font-size:85%;">
        <tr valign="top">
            <td align="left">
             <script type="text/javascript">
					$(document).ready(function() {
						$("#catIdd").focus();
						$('#tranDateFrom').datepicker({									
							dateFormat : 'dd-m-yy'
						});
						$('#tranDateTo').datepicker({									
							dateFormat : 'dd-m-yy'
						});
						$("#goBtn").click(function() {
								var SUPPLIER_ID  	= $("#SUPPLIER_ID").val();
								var BRANCH_ID  		= $("#catIdd").val();
								var tranDateFrom  	= $("#tranDateFrom").val();
								var tranDateTo  	= $("#tranDateTo").val();
								 var listOfProduct	= $("#nodeDepth").val();
								if(SUPPLIER_ID == '') {
									alert('Please Select supplier first.');
									$('#noDataFound').fadeOut('slow');
									$('#preloader').fadeIn('slow');
									$('#noDataFound').fadeIn('slow');
									$('#preloader').fadeOut('slow');
									$("#SUPPLIER_ID").focus();
									return false;
								}
								if(BRANCH_ID == '') {
									alert('Please Insert category.');
									$('#noDataFound').fadeOut('slow');
									$('#preloader').fadeIn('slow');
									$('#noDataFound').fadeIn('slow');
									$('#preloader').fadeOut('slow');
									$("#PARENT_CATEGORY").focus();
									return false;
								}
								
								var tranDateFrom  	= $("#tranDateFrom").val();
								var tranDateTo  	= $("#tranDateTo").val();
								var printView 		= 'view';
								
								$.post('/srstockreport/getSrStockReport',{'branch_id': BRANCH_ID,'printView':printView,'tranDateFrom':tranDateFrom,'tranDateTo':tranDateTo,'listOfProduct':listOfProduct,'SUPPLIER_ID':SUPPLIER_ID}, function(data) {
								//$.getJSON('/srstockreport/getSrStockReport',{'branch_id': BRANCH_ID,'printView':printView,'tranDateFrom':tranDateFrom,'tranDateTo':tranDateTo,'listOfProduct':listOfProduct}, function(data) {
									//alert(data);
								if(data.length > 0)  {
									//alert(data);
									$('#noDataFound').fadeOut('slow');
									$('#preloader').fadeIn('slow');
									$('#showMarginableScripHere').fadeIn('slow');
									$('#showMarginableScripHere').html(data);
									$('#showMarginableScripHere').fadeIn("slow");
									$('#preloader').fadeOut('slow');
								} else  {
									$('#noDataFound').fadeOut('slow');
									$('#preloader').fadeIn('slow');	
								}	
							});
						});
					});
					
					function checkCalender(thisDate,businessDate){
						var fromDate = String($("#tranDateFrom").val());
						var toDate = String($("#tranDateTo").val());
						if((fromDate != '') && (toDate != '')){							
							var tempFromDate = fromDate.split('-'); 
							var tempToDate = toDate.split('-');							
							var a = tempFromDate[1]+'/'+tempFromDate[0]+'/'+tempFromDate[2];
							var b = tempToDate[1]+'/'+tempToDate[0]+'/'+tempToDate[2];													
							if((dates.compare(b,a) == 1) || (dates.compare(b,a) == 0)) {
								return true;
							} else {
								alert('Invalid Date Range!');
								$("#tranDateFrom").attr("value",businessDate);
								$("#tranDateTo").attr("value",businessDate);
								return false;
							}
						}
					}
					
					function coa_code_suggest(inputString) 
					{
						//alert(inputString);
						//alert(no);
						if(inputString.length == 0)
						{
							$('#empIdSuggestions'+no).fadeOut();
						} 
						else 
						{
							//$.post("ajax/suggest_ref_coa_code.php", {queryString: inputString, no : no}, 
							$.post('/srstockreport/getSuggestRefCOAName',{queryString: inputString},
							function(data)
							{
								//alert(data);
								if(data.length >0) 
								{
									$('#suggestingEmpIdList').html(data);
									$('#empIdSuggestions').fadeIn("slow");
									
								}
							});
						}
					}
					
					function fill_id(thisValue) {
					   var coaCodeHeadName = thisValue;
					   if(coaCodeHeadName == '') {
							document.getElementById('PARENT_CATEGORY').value = '';
							document.getElementById('nodeDepth').value = '';
							document.getElementById('catIdd').value = '';
							return false;
						}
						var myArray = coaCodeHeadName.split(','); 
						document.getElementById('PARENT_CATEGORY').value = myArray[1];
						document.getElementById('nodeDepth').value = myArray[2];
						document.getElementById('catIdd').value = myArray[0];
					   $('#empIdSuggestions').fadeOut();
					}
					
                </script>
                 <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;'>
					<legend style='border:0px;'>Search By</legend>
                        <form name="InvestorCurrentUnitHoldingForm" method="post" action="IncomeStatement.php">
                            <table border="0" cellpadding="3" cellspacing="0" width="100%">
                              
                                <tr>
                                    <td width="23%">&nbsp;</td>
                                    <td width="17%">Supplier Name</td>
                                    <td width="1%">: </td>
                                    <td width="59%">
										<?php echo $this->formRow($form->get('SUPPLIER_ID')); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="23%">&nbsp;</td>
                                    <td width="17%">Category Name</td>
                                    <td width="1%">: </td>
                                    <td width="59%">
										<div style='position:relative;'>
                                            <input name='PARENT_CATEGORY' type='text'  id='PARENT_CATEGORY'  style='width:150px;font-family:Tahoma, Geneva, sans-serif;' value='' autocomplete='off' onkeyup='coa_code_suggest(this.value);'/>
                                            <input name='nodeDepth' type='hidden'  id='nodeDepth' value='' />
                                            <input name='catIdd' type='hidden'  id='catIdd' value='' />
                                           <div id='empIdSuggestions' style='display:none;width:150px; height:250px;' class='ClassempIdSuggestions'>
                                                <div id='suggestingEmpIdList' class='ClasssuggestingEmpIdList'>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>
                                     From</td>
                                    <td> : </td>
                                    <td>
                                    <?php echo $this->formRow($form->get('tranDateFrom')); ?> &nbsp;&nbsp;
                                    To&nbsp;
                                    <?php echo $this->formRow($form->get('tranDateTo')); ?>
                                    </td>
                                </tr>
                                 <tr>
                                     <td>&nbsp;</td>
                                     <td>&nbsp;</td>
                                     <td>&nbsp;</td>
                                     <td>
										<input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type='button' name='goBtn' id='goBtn' value='GO'/>
                                        <input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type='reset' name='Reset' id='Reset' value='Reset'/>
                                     </td>
                                 </tr>
                            </table>
                        </form>
                </fieldset>
               
            </td>
        </tr>
        <tr valign="top">
            <td align="left" style="padding-right:30px;">
             <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;'>
				<legend style='border:0px;'>Stock Report</legend>
                <div id="viewPTBStatement">
                 	<table border="0" cellpadding="3" cellspacing="0" width="100%">
                            <tr id="noDataFound" valign="middle">
                                <td width="100%" align="center" style="font-weight:bold; color:#F00;">No Information Found!</td>
                            </tr>
                            <tr>
                                <td id="preloader" style='height:100px; padding:0px; text-align:center; display:none;'>
                                    <h4 id='msg' style="font-weight:normal;margin-top:0px;">Please, wait while in process . . .</h4>
                                    <span>
                                        <img src="../img/preloader2.gif" style="width:40px;" />
                                    </span>
                                </td>
                            </tr>
                    </table>
                </div>
                <div id="showMarginableScripHere" style="display:none;">
                	<table border="0" cellpadding="3" cellspacing="0" width="100%">
                            <tr>
                                <td id="preloader1" style='height:100px; padding:0px; text-align:center; display:none;'>
                                    <h4 id='msg1' style="font-weight:normal;margin-top:0px;">Please, wait while in process . . .</h4>
                                    <span>
                                        <img src="../img/preloader2.gif" style="width:40px;" />
                                    </span>
                                </td>
                            </tr>
                    </table>
                </div>
                </fieldset>
            </td>
        </tr>
    </table>
	<?php 
	//echo $this->formCollection($form);
	echo $this->form()->closeTag();
	?>