<?php if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
?>
<?php
	$coaTitle = 'Add Supplier Wise Product';
	$this->headTitle($coaTitle);
	$form = $this->form;
	$form->setAttribute('action',$this->url('suppwisecategory'));
	$form->prepare();	
	echo $this->form()->openTag($form);
?>
<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($coaTitle); ?></h1>
 <table width="95%" border="0" cellspacing="1" cellpadding="10" style="font-family:Tahoma, Geneva, sans-serif;margin:0px auto 0px auto; font-size:85%;">
    <tr valign="top">
        <td align="left">
         <script type="text/javascript">
                $(document).ready(function() {
                    $("#SUPPLIER_INFO_ID").focus();
                    $("#goBtn").click(function() {
                            var SUPPLIER_INFO_ID  	= $("#SUPPLIER_INFO_ID").val();
							var SUPPLIER_INFO_NAME  = $( "#SUPPLIER_INFO_ID option:selected" ).text();
                            if(SUPPLIER_INFO_ID == '') {
                                alert('Please Select Supplier first.');
                                $('#noDataFound').fadeOut('slow');
                                $('#preloader').fadeIn('slow');
                                $('#noDataFound').fadeIn('slow');
                                $('#preloader').fadeOut('slow');
                                $("#SUPPLIER_INFO_ID").focus();
                                return false;
                            }
$.post('/suppwisecategory/getProductInfo',{'SUPPLIER_INFO_ID': SUPPLIER_INFO_ID,'SUPPLIER_INFO_NAME': SUPPLIER_INFO_NAME}, function(data) {
//$.getJSON('/suppwisecategory/getProductInfo',{'branch_id': BRANCH_ID,'tranDateFrom':tranDateFrom,'tranDateTo':tranDateTo,'printView':printView}, function(data) {
                            if(data.length > 0) 
                                {
                                    //alert(data);
                                    $('#noDataFound').fadeOut('slow');
                                    $('#preloader').fadeIn('slow');
                                    $('#showMarginableScripHere').fadeIn('slow');
                                    $('#showMarginableScripHere').html(data);
                                    $('#showMarginableScripHere').fadeIn("slow");
                                    $('#preloader').fadeOut('slow');
                                }
                            else 
                                {
                                    $('#noDataFound').fadeOut('slow');
                                    $('#preloader').fadeIn('slow');	
                                }	
                        });
                    });
                });
                
                function checkCalender(thisDate,businessDate){
                    var fromDate = String($("#tranDateFrom").val());
                    var toDate = String($("#tranDateTo").val());
                    if((fromDate != '') && (toDate != '')){							
                        var tempFromDate = fromDate.split('-'); 
                        var tempToDate = toDate.split('-');							
                        var a = tempFromDate[1]+'/'+tempFromDate[0]+'/'+tempFromDate[2];
                        var b = tempToDate[1]+'/'+tempToDate[0]+'/'+tempToDate[2];													
                        if((dates.compare(b,a) == 1) || (dates.compare(b,a) == 0)) {
                            return true;
                        } else {
                            alert('Invalid Date Range!');
                            $("#tranDateFrom").attr("value",businessDate);
                            $("#tranDateTo").attr("value",businessDate);
                            return false;
                        }
                    }
                }
                
            </script>
             <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;'>
                <legend style='border:0px;'>Search By</legend>
                    <form name="InvestorCurrentUnitHoldingForm" method="post" action="SuppWiseCategoryController.php">
                        <table border="0" cellpadding="3" cellspacing="0" width="100%">
                            <tr>
                                <td width="23%">&nbsp;</td>
                                <td width="17%">Supplier</td>
                                <td width="1%">: </td>
                                <td width="59%">
                                    <?php echo $this->formRow($form->get('SUPPLIER_INFO_ID')); ?>
                                </td>
                            </tr>
                            <tr>
                                 <td>&nbsp;</td>
                                 <td>&nbsp;</td>
                                 <td>&nbsp;</td>
                                 <td>
                                    <input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type='button' name='goBtn' id='goBtn' value='Load Product'/>
                                    <input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type='reset' name='Reset' id='Reset' value='Reset'/>
                                 </td>
                             </tr>
                        </table>
                    </form>
            </fieldset>
           
        </td>
    </tr>
    <tr valign="top">
        <td align="left" style="padding-right:30px;">
         <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;'>
            <legend style='border:0px;'>Product Information</legend>
            <form name="InvestorCurrentUnitHoldingForm" method="post">
            <div id="viewPTBStatement">
                <table border="0" cellpadding="3" cellspacing="0" width="100%">
                        <tr id="noDataFound" valign="middle">
                            <td width="100%" align="center" style="font-weight:bold; color:#F00;">No Information Found!</td>
                        </tr>
                        <tr>
                            <td id="preloader" style='height:100px; padding:0px; text-align:center; display:none;'>
                                <h4 id='msg' style="font-weight:normal;margin-top:0px;">Please, wait while in process . . .</h4>
                                <span>
                                    <img src="../img/preloader2.gif" style="width:40px;" />
                                </span>
                            </td>
                        </tr>
                </table>
            </div>
            <div id="showMarginableScripHere" style="display:none;">
                <table border="0" cellpadding="3" cellspacing="0" width="100%">
                        <tr>
                            <td id="preloader1" style='height:100px; padding:0px; text-align:center; display:none;'>
                                <h4 id='msg1' style="font-weight:normal;margin-top:0px;">Please, wait while in process . . .</h4>
                                <span>
                                    <img src="../img/preloader2.gif" style="width:40px;" />
                                </span>
                            </td>
                        </tr>
                </table>
            </div>
            </form>
            </fieldset>
        </td>
    </tr>
</table>
<?php echo $this->form()->closeTag(); ?>