<?php
	$title = 'Delete Supplier Wise Product';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
	'<?php echo $this->escapeHtml($suppwisecategory->CATEGORY_NAME)?>'?
</p>
<?php
	$url = $this->url('suppwisecategory', array(
		'action'	=> 'delete',
		'id'		=> $suppwisecategory->SUPP_WISE_CATEGORY_ID,
	));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
    	<input type="hidden" name="id" value="<?php echo (int) $suppwisecategory->SUPP_WISE_CATEGORY_ID;?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>