<?php
	$title = 'Edit SR and Retailer Map';
	$this->headTitle($title);
?>
 <script type="text/javascript">
	 $(document).ready(function(){
			$("#DESIGNATION_ID").focus();
		});
	 function doValidationSrRetailerMapForm() {
		 if(document.getElementById('DESIGNATION_ID').value=="") {
			//alert("Please select Designation!");
			document.getElementById('DESIGNATION_ID').focus();
			return false;
		}
		if(document.getElementById('EMPLOYEE_ID').value=="") {
			//alert("Please select SR name!");
			document.getElementById('EMPLOYEE_ID').focus();
			return false;
		}
		/*if(document.getElementById('RETAILER_ID').value=="") {
			alert("Please select Retailer name!");
			document.getElementById('RETAILER_ID').focus();
			return false;
		}*/
		if(!confirm('Are you sure, you want to proceed?')){
			return false;
		}
		return true;
	}
	
	function getEmployeeName(designationId) {
		//alert(designationId);
		//$.post('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
		$.getJSON('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
				//alert(j);
				if(j.length>0)
				{
					var options = '';
					options += '<option value="">Select Emp. Name</option>';
					for (var i = 0; i < j.length; i++) {
					options += '<option value="' + j[i].optionValue + '">' + j[i].optionDisplay + '</option>';
					}
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
				else
				{
					options = '<option value="">Select Emp. Name</option>';
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
			});
	}
	
	$(document).ready(function(){
		$("#EMPLOYEE_ID").click(function(){
			var employeeID 	= $("#EMPLOYEE_ID").val();
			if(employeeID==''){
				$("#showTemplateDefaultCharge1").html('');
			}
		});
		$("#EMPLOYEE_ID").change(function(){
				$('#showTemplateDefaultCharge1').fadeIn('slow');									
				$('#preloader').fadeIn('slow');
				if ($(this).val() == '') {
					$('#EMPLOYEE_ID').val('');
					return false;
				}
				
				var url = '/srretailermap/getRetailerListData?id=' + $(this).val();
				//$.post(url, function(data) {
				$.getJSON(url, function(data) {
				    //alert(data);
							
					var chargeTable = '';
					var k = 1;
					if(data.length>0) {
						//alert(data);
						chargeTable += '<table border="0" width="100%" class="table" cellpadding="2" cellspacing="2" style="font-size:100%;">';
						chargeTable +='<tr>';
						chargeTable +='<td width="5%">' + '<input type="checkbox" name="chargeAllCheck" onchange="check(\'investor_charge\')" id="investor_charge_all" value="" disabled="disabled"  />' + '</td>';
						chargeTable +='<td width="35%"><b>SHOP</b></td>';
						chargeTable +='<td width="30%" style="text-align:left;"><b>RET. Name</b></td>';
						chargeTable +='<td width="30%" style="text-align:left;"><b>ADDRESS</b></td>';
						chargeTable +='</tr>';
						for (var i = 0; i < data.length; i++) {
							var tcid = data[i].RETAILER_ID;					
							
							chargeTable +='<tr id="row'+k+'">';
							if(data[i].END_DATE=='DeActive'){
								chargeTable += '<td>' + '<input type="checkbox" name="RETAILER_ID[]" onclick="check_me('+k+','+data[i].SR_RETAILER_MAP_ID+');" id="investor_charge'+k+'" value="'+ data[i].SR_RETAILER_MAP_ID +'" />' + '</td>';
							}else{
								chargeTable += '<td>' + '<input type="checkbox" checked="checked" name="RETAILER_ID[]" onclick="check_me('+k+','+data[i].SR_RETAILER_MAP_ID+');" id="investor_charge'+k+'" value="'+ data[i].SR_RETAILER_MAP_ID +'" />' + '</td>';
							}
							
							chargeTable += '<td>' + data[i].SHOP_NAME + '</td>';
							chargeTable += '<td>' + data[i].NAME + '</td>';
							chargeTable += '<td>' + data[i].ADDRESS + '</td>';
							chargeTable += '</tr>';
							k++;
						}							
						chargeTable += '</table>';
						//$('#showTemplateDefaultCharge1').fadeIn('slow');
						$("#showTemplateDefaultCharge1").html('');
						$("#showTemplateDefaultCharge1").html(chargeTable);						
						//$('#showTemplateDefaultCharge1').html(data);
						//$('#showTemplateDefaultCharge1').fadeIn("slow");
						$('#preloader').fadeOut('slow');
						document.getElementById('num_of_investor_charge').value = k;
						//$('#showTotalAmount').fadeIn('slow');
					} else {
						chargeTable += '<table width="100%">';
						chargeTable +='<tr>';
						chargeTable +='<td>No Charge Found!</td>';
						chargeTable += '</tr>';
						chargeTable += '</table>';
						$("#showTemplateDefaultCharge1").html('');				
						$("#showTemplateDefaultCharge1").html(chargeTable);
						//$('#showTotalAmount').fadeOut('slow');
					}
					return true;
				});
			});
	 });
	 $(document).ready(function(){
			$("#DESIGNATION_ID").focus();
		});
		
		function check_me(id,id2){
			//alert(id2);
			var url = '/srretailermap/getRetailerListDataEdit?id=' + id2;
			$.getJSON(url, function(data) {
				alert(data+ " Successfully");
			});
			
		}
 </script>
<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url(
		'srretailermap',
		array(
			'action'	=> 'edit',
			'id'		=> $this->id,
		)));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('SR_RETAILER_MAP_ID'));
?>
<table width="70%" class="frmTbl" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
        <tr valign="top">
            <td colspan="4" align="center"><h1><?php echo $this->escapeHtml($title);?></h1></td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">Designation</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('DESIGNATION_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">SR Name</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('EMPLOYEE_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        
      	<tr valign="top">
            <td align="left" colspan="4">
                <div id="showTemplateDefaultCharge1" style="width:100%;display:none;">
                	<table border="0" cellpadding="3" cellspacing="0" width="100%">
                            <tr>
                                <td id="preloader" style='height:100px; padding:0px; text-align:center; display:none;'>
                                    <h4 id='msg1' style="font-weight:normal;margin-top:0px;">Please, wait while retailer list is loading . . .</h4>
                                    <span>
                                        <img src="../img/preloader2.gif" style="width:40px;" />
                                    </span>
                                </td>
                            </tr>
                    </table>
                </div>
            </td>
        </tr>
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right"></td>
            <td align="left"></td>
            <td align="left"></td>
        </tr>
        <tr valign="top">
            <td align="right">&nbsp;</td>
            <td align="right">&nbsp;</td>
            <td align="left">&nbsp;</td>
            <!--<td align="left">
				<?php echo $this->formSubmit($form->get('submit'));?>
                <input style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;" type="reset"  name="Reset" value="Reset" />
            </td>-->
        </tr>
    </table>
<?php
	echo $this->form()->closeTag();
?>

<script>
$('form#srRetailerMap input, select, textarea, button').keydown(function (e) {
			if (e.keyCode == 13) {
				var inputs = $(this).parents("form").eq(0).find(":input, select, textarea, button");
				if (inputs[inputs.index(this) + 1] != null) {                    
					inputs[inputs.index(this) + 1].focus();
					
				}else{
					doValidationSrRetailerMapForm();
				}
				
				e.preventDefault();
				return false;
			}
		});
</script>