<?php
	$title = 'Add SR Target';
	$this->headTitle($title);
	?>

	<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('srtarget',array('action' => 'add')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('SR_TARGET_ID'));
?>
<table width="70%" class="frmTbl" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
        <tr valign="top">
            <td colspan="4" align="center"><h1><?php echo $this->escapeHtml($title);?></h1></td>
        </tr>
         <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">Designation</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('DESIGNATION_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">SR Name</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('EMPLOYEE_ID')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
         <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">Start Date</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('START_DATE')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
         <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">End Date</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('END_DATE')); ?>
            	<sup style="color:red;">*</sup>
            </td>
        </tr>
       <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">Remarks</td>
            <td align="left">:</td>
            <td align="left">
            	<?php echo $this->formRow($form->get('REMARKS')); ?>
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="left">&nbsp;</td>
            <td align="left">&nbsp;</td>
        </tr>
        <tr valign="middle">
            <td colspan="4" align="center">
            	<div id="trade_file_view_details">
                    <div style="margin-bottom:4px;width:80%; font-family:Tahoma, Geneva, sans-serif;" class="clonedInputForScripList">
                        <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
                            <legend style="border:0px;" id="stock1">Add Target List <input type="text" name="closest_position" id="closest_position1" class="closest_position" value="1" readonly="readonly" size="2" style="border:0px;font-weight:bold; width:40px;"/></legend>
                            <table width="80%" class="frmTbl" border="0" style="font-family:Tahoma, Geneva, sans-serif;font-size:100%;">
                                <tr>
                                    <td colspan="3" align="right" valign="top">
                                        <input style="font-family:Tahoma, Geneva, sans-serif;font-size:100%;" class="btnDelMoreScripList"  disabled="disabled" type="image" src="../img/cancel.png">	
                                    </td>
                                </tr>
                                <tr valign="middle">
                                    <td align="right">Target From</td>
                                    <td align="left">:</td>
                                    <td align="left">
                                       <?php echo $this->formRow($form->get('TARGET_FROM[]')); ?> %
                                        
                                    </td>
                                </tr>
                                <tr valign="middle">
                                    <td align="right">Target To</td>
                                    <td align="left">:</td>
                                    <td align="left">
                                            <?php echo $this->formRow($form->get('TARGET_TO[]')); ?> %
                                    </td>
                                </tr>
                                <tr valign="middle">
                                    <td align="right">Target Value</td>
                                    <td align="left">:</td>
                                    <td align="left">
                                            <?php echo $this->formRow($form->get('TARGET_VALUE[]')); ?>
                                    </td>
                                </tr>
                            </table>
                        </fieldset>
                    </div>
                </div>
            </td>
        </tr>
        <tr valign="top">
            <td align="right" colspan="4">
        		<input style="font-family:Tahoma, Geneva, sans-serif;font-size:100%;" id="btnAddMoreScripList" value="Add More" type="button">
            </td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right"></td>
            <td align="left"></td>
            <td align="left"></td>
        </tr>
        <tr valign="middle">
            <td align="right">&nbsp;</td>
            <td align="right">&nbsp;</td>
            <td align="left">&nbsp;</td>
            <td align="left">
				<?php echo $this->formSubmit($form->get('submit'));?>
                <input name="TOTAL_SCRIP_LIST" id="TOTAL_SCRIP_LIST" type="hidden" value="2" />
               
			   
            </td>
        </tr>
    </table>
<?php
	echo $this->form()->closeTag();
?>

     <script type="text/javascript" language="javascript" >
	$(document).ready(function() {
		$("#EMPLOYEE_ID").focus();
		$('#START_DATE').datepicker({									
			dateFormat : 'dd-mm-yy'
		});
		$('#END_DATE').datepicker({									
			dateFormat : 'dd-mm-yy'
		});	
		
	});
  function checkCalender(thisDate,businessDate) {
				//alert(String(businessDate));
				var fromDate = String($("#START_DATE").val());
				var toDate = String($("#END_DATE").val());
				if((fromDate != '') && (toDate != '')){                        
					var tempFromDate = fromDate.split('-'); 
					var tempToDate = toDate.split('-');                        
					var a = tempFromDate[1]+'/'+tempFromDate[0]+'/'+tempFromDate[2];
					var b = tempToDate[1]+'/'+tempToDate[0]+'/'+tempToDate[2];
					if((dates.compare(b,a) == 1) || (dates.compare(b,a) == 0)) {
						return true;
					} else {
						alert('Invalid Date Range!');
						$("#END_DATE").attr("value",businessDate);
						return false;
					}
				}
			}
	 $(document).ready(function(){
			$("#DESIGNATION_ID").focus();
		});
	 function doValidationSrTargetForm() {
		if(document.getElementById('DESIGNATION_ID').value=="") {
			//alert("Please select Designation!");
			document.getElementById('DESIGNATION_ID').focus();
			return false;
		}
		if(document.getElementById('EMPLOYEE_ID').value=="") {
			//alert("Please select SR name!");
			document.getElementById('EMPLOYEE_ID').focus();
			return false;
		}
		
		if(document.getElementById('START_DATE').value=="") {
			//alert("Please select Date From!");
			document.getElementById('START_DATE').focus();
			return false;
		}
		if(document.getElementById('END_DATE').value=="") {
			//alert("Please select Date To!");
			document.getElementById('END_DATE').focus();
			return false;
		}
		if(!confirm('Are you sure, you want to proceed?')){
			return false;
		}
		return true;
	}
		
var inputs = 2;	
$('#btnAddMoreScripList').click(function() {		
	
	$('.btnDelMoreScripList:disabled').removeAttr('disabled');
	var c = $('.clonedInputForScripList:first').clone(true);
	
	
	c.find('input:text#TARGET_FROM_1').attr({
											'value':'',
											'id':'TARGET_FROM_'+inputs
										});
	c.find('input:text#TARGET_TO_1').attr({
											'value':'',
											'id':'TARGET_TO_'+inputs
										});
	c.find('input:text#TARGET_VALUE_1').attr({
											'value':'',
											'id':'TARGET_VALUE_'+inputs
										});												

	c.find('input:hidden#closest_position1').attr({
										'id':'closest_position'+inputs,
										'value':inputs
									});															
												
	$('.clonedInputForScripList:last').after(c);
	
	
	inputs++;
	$("#TOTAL_SCRIP_LIST").attr('value',inputs);
});

$('.btnDelMoreScripList').click(function() {
	if (confirm('Continue Delete?')) {
		var colsest_pos = $(this).closest('.clonedInputForScripList').find('.closest_position').val();
		$(this).closest('.clonedInputForScripList').remove();
		var counter = 1;
		for(var i=1;i<inputs;i++) {
			if(i == colsest_pos)
			continue;
			
			$("#trade_file_view_details").find('input:text#TARGET_FROM_'+i).attr({
																	'id':"TARGET_FROM_"+counter
																});	
			$("#trade_file_view_details").find('input:text#TARGET_TO_'+i).attr({
																	'id':"TARGET_TO_"+counter
																});	
			$("#trade_file_view_details").find('input:text#TARGET_VALUE_'+i).attr({
																	'id':"TARGET_VALUE_"+counter
																});														
																																																																																																										
			$("#trade_file_view_details").find('input:text#closest_position'+i).attr({
														'value':counter,
														'id':'closest_position'+counter
													});
			counter++;
		}
		--inputs;
		$("#TOTAL_SCRIP_LIST").attr('value',inputs);
		$('.btnDelMoreScripList').attr('disabled',($('.clonedInputForScripList').length  < 2));
		return false;
	}
	else{
		return false;
	}
});		
	
	function getEmployeeName(designationId) {
		//alert(designationId);
		//$.post('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
		$.getJSON('/srzonemap/getEmpName',{designationId: designationId}, function(j) {
				//alert(j);
				if(j.length>0)
				{
					var options = '';
					options += '<option value="">Select Emp. Name</option>';
					for (var i = 0; i < j.length; i++) {
					options += '<option value="' + j[i].optionValue + '">' + j[i].optionDisplay + '</option>';
					}
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
				else
				{
					options = '<option value="">Select Emp. Name</option>';
					$("select#EMPLOYEE_ID").html('');
					$("select#EMPLOYEE_ID").html(options);
				}
			});
	} 
	 
	</script>
	
	<script>
$('form#srTarget input, select, textarea, button').keydown(function (e) {
			if (e.keyCode == 13) {
				var inputs = $(this).parents("form").eq(0).find(":input, select, textarea, button");
				if (inputs[inputs.index(this) + 1] != null) {                    
					inputs[inputs.index(this) + 1].focus();
					
				}else{
					doValidationSrTargetForm();
				}
				
				e.preventDefault();
				return false;
			}
		});
</script>