<?php
	$title = 'Delete SR Target';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
	'<?php //echo $this->escapeHtml($srTarget->NAME)?>'?
</p>
<?php
	$url = $this->url('srtarget', array(
		'action'	=> 'delete',
		'id'		=> $srTarget->SR_TARGET_ID,
	));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
    	<input type="hidden" name="id" value="<?php echo (int) $srTarget->SR_TARGET_ID;?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>