<?php
	if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
	$title = 'Account Entry Edit';
	$this->headTitle($title);
	?>
	<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($title);?></h1>
	<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('generalaccountentryedit'));
	$form->prepare();	
	echo $this->form()->openTag($form);
?>
<table width="100%" border="0" cellspacing="1" cellpadding="5" style="margin:0px auto 0px auto; font-family:Tahoma, Geneva, sans-serif;">
    <tr valign="top">
        <td align="left">
            <table width="100%"  border="0" cellspacing="0" cellpadding="0" align="center">
                <tr valign="top">
                    <td align="left">
                             <script type="text/javascript">
							 	$(document).ready(function() {
									$('#TRANSACTION_DATE2').datepicker({									
										dateFormat : 'dd-mm-yy'
									});
									$('#tranDateFrom').datepicker({									
										dateFormat : 'dd-mm-yy'
									});
									$('#tranDateTo').datepicker({									
										dateFormat : 'dd-mm-yy'
									});
									
									$("#goBtn").click(function(){
										var BRANCH_ID  		= $("#BRANCH_ID").val();
										var tranDateFrom  	= $("#tranDateFrom").val();
										var tranDateTo  	= $("#tranDateTo").val();
										var voucherData  	= $("#VoucherNo").val();
										if(BRANCH_ID=='') {
											alert('Please Select Branch.');
											$("#BRANCH_ID").focus();
											return false;
										}
										if(voucherData == '') {
											alert('Please Select Voucher No.');	
											$("#VoucherNo").focus();
											return false;
										}
										//$.post('/generalaccountentryedit/getAccountsEditForEod',{'BRANCH_ID': BRANCH_ID, 'tranDateFrom' :tranDateFrom, 'tranDateTo' :tranDateTo,  'voucherData' : voucherData}, function(data) {
										$.getJSON('/generalaccountentryedit/getAccountsEditForEod',{'BRANCH_ID': BRANCH_ID, 'tranDateFrom' :tranDateFrom, 'tranDateTo' :tranDateTo,  'voucherData' : voucherData}, function(data) {
											//alert('hit erherer');
											if(data.length >0)  {
												//alert(data);
												$('#noDataFound').fadeOut("slow");
												$('#viewDailyTransaction').html(data);
												$('#viewDailyTransaction').fadeIn("slow");
												blankAllFields();
											}
										});
									});
								});
								
								function editVoucherNumber(VoucherNo,transactionNumber) {						
									if(confirm("Are you sure you want to delete voucher number of "+VoucherNo+"?")) {
										$("#loading").show();
										$("#loading").html("<div class='error_msg'>Please, wait your voucher number cancellation is on process...</div>");
										//$.post('/generalaccountentryedit/getRemoveVoucherNumber',{'VoucherNo': VoucherNo,'transactionNumber':transactionNumber}, function(data) {
										$.getJSON('/generalaccountentryedit/getRemoveVoucherNumber',{'VoucherNo': VoucherNo,'transactionNumber':transactionNumber}, function(data) {											
											//alert(data);
											$("#loading").html(data);
											$('#viewDailyTransaction').html(data);
											$('#viewDailyTransaction').fadeIn("slow");
										});	
									}
								}
								
								function generateVoucherNoList() {
									//alert('hi there');
									var vType 			= $('input[name=voucherType]:radio:checked').val();
									var BRANCH_ID  		= $("#BRANCH_ID").val();
									//var tranDateFrom  	= $("#TRANSACTION_DATE2").val();
									var tranDateFrom  	= $("#tranDateFrom").val();
									var tranDateTo  	= $("#tranDateTo").val();
									var voucherTypeCBCond 	= $('input[name=voucherTypeCBCond]:radio:checked').val();
									$("#voucherListA").attr("checked",true);
									$('#VoucherNo').show();
									$('#preloaderQuery').fadeIn('slow');
									//alert('adsfadsfd');
									$('#showCustVoucherNo').hide();
									//$.post('/generalaccountentryedit/getVoucherNumberForAccountsEdit',{'BRANCH_ID': BRANCH_ID, 'vType' : vType, 'tranDateFrom' :tranDateFrom, 'tranDateTo' :tranDateTo, 'voucherTypeCBCond' :voucherTypeCBCond}, function(j) {
									$.getJSON('/generalaccountentryedit/getVoucherNumberForAccountsEdit',{'BRANCH_ID': BRANCH_ID, 'vType' : vType, 'tranDateFrom' :tranDateFrom, 'tranDateTo' :tranDateTo, 'voucherTypeCBCond' :voucherTypeCBCond}, function(j) {
										if(j.length>0) {
											//alert(j);
											var options='';
											for (var i = 0; i < j.length; i++) {
												var id = j[i].optionValue;
												var name = j[i].optionDisplay;
												options += '<option value="' + id + '" selected="selected">' + name + '</option>';
											}
											$("#VoucherNo").html('');
											$("#VoucherNo").html(options);
											$('#preloaderQuery').fadeOut('slow');
										} else {
											options = '<option value="" selected="selected">Select</option>';
											$("#VoucherNo").html('');
											$("#VoucherNo").html(options);
											$('#preloaderQuery').fadeOut('slow');
										}
									});
								}
								
								function bankNameSuggestForCashAtBank(inputString,id) {
									if(inputString.length == 0)
									{
										$('#BankNameSuggestions').fadeOut();
									} 
									else 
									{
										$.post("/generalaccountentryedit/getSuggestBankName", {queryString: inputString,id: id}, 
										//$.getJSON("/generalaccountentryedit/getSuggestBankName",{queryString: inputString,},
										function(j)
										{
											if(j.length >0) 
											{
												//alert(j);
												//document.getElementById('BankNameSuggestionsList'+id).html(j);
												//document.getElementById('BankNameSuggestions'+id).fadeIn("slow");
												$('#BankNameSuggestionsList').html(j);
												$('#BankNameSuggestions').fadeIn("slow");
												
											} else{
												$('#BankNameSuggestions').fadeOut();
											}
										});
									}
								}
								
								function fill_bank_name(thisValue,id){
								   if(thisValue == ''){
										document.getElementById(id).value = '';
										return false;
									}
									document.getElementById(id).value = thisValue;
									$('#BankNameSuggestions').fadeOut();
								}
								
								function bankNameSuggestForCashInHand(inputString,id) {
									if(inputString.length == 0)
									{
										$('#BankNameSuggestions'+id).fadeOut();
									} 
									else 
									{
										$.post("/generalaccountentryedit/getSuggestBankNameForCIH", {queryString: inputString,id: id}, 
										//$.getJSON("/generalaccountentryedit/getSuggestBankNameForCIH",{queryString: inputString,},
										function(j)
										{
											if(j.length >0) 
											{
												$('#BankNameSuggestionsListCIH').html(j);
												$('#BankNameSuggestionsCIH').fadeIn("slow");
												
											} else{
												$('#BankNameSuggestionsCIH').fadeOut();
											}
										});
									}
								}
								function fill_bank_nameCIH(thisValue,id){
								   if(thisValue == ''){
										document.getElementById(id).value = '';
										return false;
									}
									document.getElementById(id).value = thisValue;
									$('#BankNameSuggestionsCIH').fadeOut();
								}
								
								function customVoucherNo_suggest(inputString) {
									if(inputString.length == 0) {
										$('#VoucherNoSuggestions').fadeOut();
									} else {
									}
								}
								
								function showHideCB(id) {
									if((id == 'voucherType3') || (id == 'voucherType7')) {
										document.getElementById('showCashBankCond').style.display = 'none';	
									} else {
										document.getElementById('showCashBankCond').style.display = '';	
									}
								}
								function checkBranch() {
									if($("#BRANCH_ID").val()=="") { 
										alert("Please select branch!");  
										$("#BRANCH_ID").focus();
									}	
								}
								function checkReset(){
									$('#viewDailyTransaction').html('');
									var options = '';
									options = '<option value="" selected="selected">Select</option>';
									$('#VoucherNo').html(options);
									$('#viewDailyTransaction').fadeOut("slow");
									$('#noDataFound').fadeIn("slow");								
								}
							 </script>   
                            <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
                                <legend style='border:0px;'>Account Entry Edit</legend>
                                <table width="100%" border="0" cellpadding="3" cellspacing="0">
                                    <tr>
                                        <td>
                                            <table width="100%" border="0" cellpadding="3" cellspacing="0" style="margin:0px auto 0px auto;font-size:100%;">	
                                                <tr valign="top">
                                                  <td width="100%" colspan="4" align="center">
                                                        <table align="center" width="70%" border="0" cellpadding="3" cellspacing="0" style="margin:0px auto 0px auto;font-size:85%;">
                                                                <tr>                                    
                                                                    <td>Branch</td>
                                                                    <td> : </td>
                                                                    <td>
                                                                        <input type="hidden" name="COMPANY_ID"  id="COMPANY_ID" value="1"/>
                                                                        <?php //echo $this->formRow($form->get('BRANCH_ID')); ?>
                                                                        <select name="BRANCH_ID" id="BRANCH_ID" onchange="generateVoucherNoList();blankAllFields();" style="padding-left:10px;font-family:Tahoma, Geneva, sans-serif;font-size:100%;">
                                                                            <option value="">~~ Please Choose ~~</option>
                                                                            <option value="1" selected="selected">Head Office</option>
                                                                        </select>
                                                                    </td>
                                                                    <td>&nbsp;</td>
                                                                </tr>
                                                                <tr>                                    
                                                                    <td>Transaction Date</td>
                                                                    <td> : </td>
                                                                    <td><?php //echo $this->formRow($form->get('TRANSACTION_DATE')); ?>
                                                                        <?php echo $this->formRow($form->get('tranDateFrom')); ?>
                                                                        <?php echo $this->formRow($form->get('tranDateTo')); ?>
                                                                        <input type="hidden" name="EFFECTED_AT_BANK" value="n"/>
                                                                        <input type="hidden" name="AUTO_TRANSACTION" value="n"/>
                                                                    </td>
                                                                    <td>&nbsp;</td>
                                                                </tr>
                                                                <tr valign="top">
                                                                     <td >Voucher</td>
                                                                     <td >:</td>
                                                                     <td colspan="2">
                            <input type="radio" name="voucherType" id="voucherType7" value="all" onclick="showHideCB(this.id);generateVoucherNoList();" checked="checked" />All<br />
                            <input type="radio" name="voucherType" id="voucherType3" value="Journal" onclick="showHideCB(this.id);generateVoucherNoList();" />Journal<br />
                            <input type="radio" name="voucherType" id="voucherType1" value="Payment" onclick="showHideCB(this.id);generateVoucherNoList();"  />Payment<br />
                            <input type="radio" name="voucherType" id="voucherType2" value="Receipt" onclick="showHideCB(this.id);generateVoucherNoList();" />Receipt<br />
                            <input type="radio" name="voucherType" id="voucherType2" value="Contra" onclick="showHideCB(this.id);generateVoucherNoList();" />Contra
                                                                                        <span id="showCashBankCond" style="display:none;">
                             <input type="radio" name="voucherTypeCBCond" value="cashBankAll" onclick="generateVoucherNoList();" checked="checked" />&nbsp;All
                             <input type="radio" name="voucherTypeCBCond" value="bank" onclick="generateVoucherNoList();"  />&nbsp;Bank
                             <input type="radio" name="voucherTypeCBCond" value="cash" onclick="generateVoucherNoList();" />Cash&nbsp;&nbsp;
                                                                        </span>
                                                                     </td>
                                                                 </tr>
                                                                  <tr valign="top">
                                                                     <td>Voucher No.</td>
                                                                     <td>:</td>
                                                                     <td colspan="2">
                                                                        <select name="VoucherNo" id="VoucherNo" onclick="checkBranch();" style="width:180px;font-size:100%;">
                                                                            <option value="">Select</option>
                                                                        </select><span id="preloaderQuery" style="display:none;"><img src="../img/preloader2.gif" style="width:40px;" /></span>
                                                                       <div style="position:relative; display:none;" id="showCustVoucherNo">
                                                                            <input name="customVoucherNo[]" size="30" id="customVoucherNo" type="text" value="" onkeyup="customVoucherNo_suggest(this.value);" />
                                                                         <div id='VoucherNoSuggestions' style='display:none; width:205px; height:205px;' class='ClassempIdSuggestions'>
                                                                                <div id='VoucherNoSuggestionsList' class='ClasssuggestingEmpIdList'>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                     </td>
                                                                 </tr>
                                                        </table>
                                                  </td>
                                              </tr>
                                              <tr>
                                                 <td colspan="4" align="center">
                                                    <input style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;" type='button' name='goBtn' id='goBtn' value='GO' class="FormBtn"/>
                                                    <input style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;" type='reset' name='Reset' id='Reset' value='Reset' class="FormBtn" onclick="checkReset();"/>
                                                 </td>
                                             </tr>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr valign="top" >
                                            <td align="center">
                                                <fieldset style='width:100%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
                                                    <legend style=" border:0px;cursor:pointer;" onClick="return ShowHide('viewcomp_minorest')">COA Record</legend>
                                                    <div id="viewDailyTransaction">
                                                        <table border="0" cellpadding="3" cellspacing="0" width="100%" >
                                                            <tr>
                                                                <td width="23%" align="center" style="font-weight:bold; color:#F00;"><p>&nbsp; </p>No Data Found! </td>
                                                            </tr>
                                                            <tr>
                                                                <td width="23%" align="center" style="font-weight:bold; color:#F00;">
                                                                    <p>&nbsp; </p>
                                                                    <p>&nbsp; </p>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </div> 
                                                    <div id="noDataFound" style="display:none;">
                                                        <table border="0" cellpadding="3" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td width="23%" align="center" style="font-weight:bold; color:#F00;"><p>&nbsp; </p>No Data Found! </td>
                                                                </tr>
                                                        </table>
                                                    </div>                                                   
                                                </fieldset>
                                            </td>
                                    </tr>
                                </table>
                        </fieldset>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    </table>
<?php
echo $this->form()->closeTag();
?>
<script type="text/javascript">
	function doValidationAccountsEditForm() {
	   //alert('hit erherer');
	   var formObject = document.generalaccountentryedit;									  
	   if(formObject.BRANCH_ID.value=="") {
			alert("Please Select Branch!");
			formObject.BRANCH_ID.focus();
			return false;
		}
		if(formObject.TRANSACTION_DATE2.value=="") {
			alert("Please Enter Transection Record Date!");
			formObject.TRANSACTION_DATE2.focus();
			return false;
		}
		
		var Totaldebit 	= 0;
		var TotalCredit = 0;
		Totaldebit 		= $('#totalDrAmount').val();
		Totaldebit 		= Number(Totaldebit.replace(/\,/g,""));
		
		TotalCredit 	= $('#totalCrAmount').val();
		TotalCredit 	= Number(TotalCredit.replace(/\,/g,""));

		Totaldebit = Totaldebit.toFixed(2);
		TotalCredit = TotalCredit.toFixed(2);			

		if(Number(Totaldebit) != Number(TotalCredit)){
			if(Totaldebit > TotalCredit) {
				var diffAmount = Totaldebit - TotalCredit;	
			} else {
				var diffAmount = TotalCredit - Totaldebit;
			}
			alert("Debit and Credit Amount mismatch! Difference : " + numberFormat('',diffAmount,2,',','.'));
			//document.getElementById('PAYMENT_AMOUNT'+2).focus();
			return false;
		}
		if(!confirm('Are you sure, you want to proceed?')){
			return false;
		}
		return true;
	}
	
	var suggestionData = {};
	suggestionData.coaCodes = {};
	
	function AddTabRow() {
		var numOfRows 	= $("#NumberOfRows").val();
		//alert(numOfRows);
		var numOfRowsId = numOfRows - 1;
		var coaCode 	= $("#coa_code"+numOfRowsId).val();
		var amount		= $("#amount"+numOfRowsId).val();
		amount			= Number(amount.replace(/[^\d\.\-\ ]/g, ''));
		coaCode 		= coaCode.substr(0,3);
		if(amount == 0) {
			return false;
		} else {
			// clone the last row in the table
			var $tr = '';//$("#ClosingBalTab").find("tbody tr:last").clone();
			
			if((coaCode == 303) || (coaCode == 304)) {
				$tr = $("#ClosingBalTab").find("#transDetails"+numOfRowsId).prev('tr').clone();
				//$('#maintable tbody>tr:last').prev('tr')
			} else {
				$tr = $("#ClosingBalTab").find("tbody tr:last").clone();
			}
			
			$tr.find("#coa_head"+numOfRowsId).attr("name", function() {
				// break the field name and it's number into two parts
				var parts = this.name.match(/(\D+)(\d+)$/);
				// create a unique name for the new field by incrementing
				// the number for the previous field by 1
				return parts[1] + ++parts[2];
			// repeat for id attributes
			}).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			}).attr("value", function(){
				return "";
			});
			
			$tr.find("#coa_codeshow"+numOfRowsId).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			});
			
			$tr.find("#coa_code"+numOfRowsId).attr("name", function() {
				// break the field name and it's number into two parts
				var parts = this.name.match(/(\D+)(\d+)$/);
				// create a unique name for the new field by incrementing
				// the number for the previous field by 1
				return parts[1] + ++parts[2];
			// repeat for id attributes
			}).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			}).attr("value", function(){
				return "";
			}).attr("checked", function(){
				return false;
			});
			
			$tr.find("#accountTypeDebit"+numOfRowsId).attr("name", function() {
				// break the field name and it's number into two parts
				var parts = this.name.match(/(\D+)(\d+)$/);
				// create a unique name for the new field by incrementing
				// the number for the previous field by 1
				return parts[1] + ++parts[2];
			// repeat for id attributes
			}).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			}).attr("value", function(){
				return "D";
			}).attr("checked", function(){
				return false;
			}).attr("onClick", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return "DrCrAmountAlign("+ parts[2] +");totalDRCRShow();";
			});
			
			$tr.find("#accountTypeCredit"+numOfRowsId).attr("name", function() {
				// break the field name and it's number into two parts
				var parts = this.name.match(/(\D+)(\d+)$/);
				// create a unique name for the new field by incrementing
				// the number for the previous field by 1
				return parts[1] + ++parts[2];
			// repeat for id attributes
			}).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			}).attr("value", function(){
				return "C";
			}).attr("checked", function(){
				return false;
			}).attr("onClick", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return "DrCrAmountAlign("+ parts[2] +");totalDRCRShow();";
			});
			
			$tr.find("#amount"+numOfRowsId).attr("name", function() {
				// break the field name and it's number into two parts
				var parts = this.name.match(/(\D+)(\d+)$/);
				// create a unique name for the new field by incrementing
				// the number for the previous field by 1
				return parts[1] + ++parts[2];
			// repeat for id attributes
			}).attr("id", function(){
				var parts = this.id.match(/(\D+)(\d+)$/);
				return parts[1] + ++parts[2];
			}).attr("onBlur", function(){
				return "numberFormat(\"amount"+numOfRows+"\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\"; AddTabRow();totalDRCRShow();";
			}).attr("value", function(){
				return "0.00";
			});
			
			$("#ClosingBalTab").find("tbody tr:last").after($tr);
			$("#coa_codeshow"+numOfRows).html('');
			$("#NumberOfRows").attr("value",Number(numOfRows)+1);
			reassignTabOrders();
			bindKeyPress();
		}
	}
	
	function blankAllFields() {
		var fundCode 	= $('#COMPANY_ID').val();
		var frm 		= $('#frm').val();
		if(fundCode != '') {									 
			//$.post('/generalaccountentryedit/getSuggestCOAPaymentRceipt',{frm : frm, fundCode : fundCode}, function(data) {
			$.getJSON('/generalaccountentryedit/getSuggestCOAPaymentRceipt',{frm : frm, fundCode : fundCode}, function(data) {
				if(data.length >0) {
					suggestionData.coaCodes = JSON.stringify(data);
					reassignTabOrders();
				} else {
					suggestionData = {};
				}
			});
		}
	}
	
	function addRemoveTransDetails(coaCode,id) {
		coaCode = coaCode.substr(0,3);
		if((coaCode == 303) || (coaCode == 304)) {
			//$("#ClosingBalTab").find("tbody tr:gt(2)").remove();
			//$("#NumberOfRows").attr("value",2);
			var tranDetails = '';
			if(coaCode == 303) {
				if($('#transDetails'+id).length > 0) {
					$('#transDetails'+id).html('');
					$('#transDetails'+id).html('<td colspan="4">Drawn on : <input name="drawnOn'+id+'" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text"/></td>');
				} else {
					tranDetails = '<tr id="transDetails'+id+'"><td colspan="4"><div style="position:relative; display:block;" id="showCustBankName">Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text" onkeyup="bankNameSuggestForCashInHand(this.value,this.id);"/><div id="BankNameSuggestionsCIH" style="display:none; width:205px; height:205px;" class="ClassempIdSuggestions"><div id="BankNameSuggestionsListCIH" class="ClasssuggestingEmpIdList"></div></div></div></td></tr>';
				}
				
			} else {
				/*$('#chq_date'+id).datepicker({									
						dateFormat : 'dd-M-yy'
					});*/
				if($('#transDetails'+id).length > 0) {
					$('#transDetails'+id).html('');
					$('#transDetails'+id).html('<td colspan="4">Instrument No. : <input maxlength="20" class="FormNumericTypeInput" type="text"  id="chequeNo'+id+'" name="chequeNo'+id+'" style="text-align:left;" value=""/>&nbsp;&nbsp;&nbsp;Date : <input name="chq_date'+id+'" class="FormDateTypeInput" id="chq_date'+id+'" type="text"  onclick="showCalender(\'chq_date\''+id+',\'chq_date\''+id+')"/>&nbsp;&nbsp;&nbsp;Drawn on : <input name="drawnOn'+id+'" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text"/></td>');
				} else {
					tranDetails = '<tr id="transDetails'+id+'"><td colspan="4"><div style="position:relative; display:block;" id="showCustBankName">Drawn on : <input name="drawnOn" class="FormTextTypeInput" id="drawnOn'+id+'" style="width:150px;" type="text" autocomplete="off" onkeyup="bankNameSuggestForCashAtBank(this.value,this.id);"/><div id="BankNameSuggestions" style="display:none; width:205px; height:205px;" class="ClassempIdSuggestions"><div id="BankNameSuggestionsList" class="ClasssuggestingEmpIdList"></div></div>&nbsp;&nbsp;Instrument No. : <input maxlength="20" class="FormNumericTypeInput" type="text"  id="chequeNo" name="chequeNo" style="text-align:left;" value=""/>&nbsp;&nbsp;&nbsp;Date : <input name="chq_date" class="FormDateTypeInput" id="chq_date'+id+'" type="text" onclick="showCalender(\'chq_date\''+id+',\'chq_date\''+id+')"/>&nbsp;&nbsp;&nbsp;</div></td></tr>';
				}
			}
			$("#ClosingBalTab").find("tbody tr:last").after(tranDetails);
			reassignTabOrders();
			bindKeyPress();
		} else {
			if($('#transDetails'+id).length > 0) {
				$('#transDetails'+id).remove();
				reassignTabOrders();
				bindKeyPress();
			}
		}
		$(document).ready(function(){
				$('#chq_date'+id).datepicker({									
					dateFormat : 'dd-mm-yy'
				});
		});
	}
	
	function callback(item,no) {
		var coaCodeHead = item.text;
		var coaCode		= item.id
		$('#coa_head'+no).attr('value',coaCodeHead);
		$('#coa_codeshow'+no).html(coaCode);
		$('#coa_code'+no).attr('value',coaCode);
		var frm      = 'p';
		var fundCode = $('#BRANCH_ID').val();
		$.post('/generalaccountentryedit/getTrialBalPayRecAmount',{'coaCode': coaCode, 'frm' : frm, 'fundCode' : fundCode }, function(data) {
		//$.getJSON('/generalaccountentryedit/getTrialBalPayRecAmount',{coaCode: coaCode, frm : frm, fundCode : fundCode }, function(data) {							
				document.getElementById('amount'+no).value = data;
		});
		//$.post("ajax/trialBalPaymentRceiptAmount.php", {coaCode: coaCode, frm : frm, fundCode : fundCode }, function(data) {
				//document.getElementById('amount'+no).value = data;
		//});
		//addRemoveTransDetails(coaCode,no);
		return false;
	}
	
	
	$(document).ready(function() {
		blankAllFields();
		reassignTabOrders();
		bindKeyPress();
	});
	function bindKeyPress() {
		$('#generalaccountentryedit input,select,textarea').unbind("keypress");
		$('#generalaccountentryedit input,select,textarea').bind('keypress',function (event){
			var currentElementId = $(this).attr('id');
			var tabindex = Number($('#'+currentElementId).attr('tabindex'));
			var parts = (currentElementId.match(/(\D+)(\d+)$/) != null) ? currentElementId.match(/(\D+)(\d+)$/) : '';
			if (event.keyCode === 13) {
				if(currentElementId == 'insertPayment') {
					if(doValidationAccountsEditForm()) {
						return true;
					} else {
						return false;
					}
					return false;
					
				} else {
					//alert('hell');
					var newTabIndex = tabindex + 1;
					if(parts[1] == 'coa_head') {
						//var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
						//$('#'+nextElementId).focus();
						//return true;
						//alert('helllllllllllll');
					} else if(parts[1] == 'amount') {
						$('#'+currentElementId).trigger('blur');
						var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
						$('#'+nextElementId).focus();
					} else {
						var nextElementId = $('[tabindex=' + newTabIndex + ']').attr('id');
						if($('#'+nextElementId).attr('type') == 'radio') {
							$('#'+nextElementId).trigger('click');
							$('#'+nextElementId).focus();
						} else {
							$('#'+nextElementId).focus();
						}
					}
					//alert('hell');
					return false;
				}
			} else {
				return true;
			}
		});
	}
	
	function reassignTabOrders(){
		//alert('safasdfd');
		var tabindex = 1;
		$('.jsonSuggestResults').remove();
		$('#generalaccountentryedit input,select,textarea').each(function() {
			var $input = $(this);
			if ($input.is(':visible')) {
				$input.attr("tabindex", tabindex);
				var coaElementId = $('[tabindex=' + tabindex + ']').attr('id');
				var parts = (coaElementId.match(/(\D+)(\d+)$/) != null) ? coaElementId.match(/(\D+)(\d+)$/) : '';
				if($.isArray(parts)){
					if(parts[1] == 'coa_head') {
						$('input#coa_head'+parts[2]).unbind("keyup");
						$('input#coa_head'+parts[2]).unbind("blur");
						$('input#coa_head'+parts[2]).unbind("focus");
						$('input#coa_head'+parts[2]).jsonSuggest(suggestionData.coaCodes, {defaultId:parts[2],onSelect:callback});
					}
				}
				tabindex++;
			}
		});
	}
	
	function DrCrAmountAlign(e){
		if(document.getElementById('accountTypeDebit'+e).checked==true){	
			document.getElementById('amount'+e).style.textAlign = 'left';
		}
		if(document.getElementById('accountTypeCredit'+e).checked==true){
			document.getElementById('amount'+e).style.textAlign = 'right'
		}
		return true;
	}
	
	function totalDRCRShow() {
		var numOfRows 	= $("#NumberOfRows").val();
		var k			= 0;
		var i			= 0;
		var Totaldebit 	= 0;
		var TotalCredit = 0;
		for(i = 1; i < numOfRows; i++){
			if((document.getElementById('accountTypeDebit'+i).checked==true) || (document.getElementById('accountTypeCredit'+i).checked==true)){
				if((document.getElementById('accountTypeDebit'+i).checked==true) && (document.getElementById('amount'+i).value !="")){
					var debitAmount 	= $('#amount'+i).val();
					debitAmount 		= Number(debitAmount.replace(/\,/g,""));
					Totaldebit      	= Totaldebit + debitAmount;
				}if((document.getElementById('accountTypeCredit'+i).checked==true) && (document.getElementById('amount'+i).value !="")){
					var creditAmount 	= $('#amount'+i).val();
					creditAmount 		= Number(creditAmount.replace(/\,/g,""));
					TotalCredit 		= TotalCredit + creditAmount;
				}									
			}	
		}
		$("#DRTOTAL").html(numberFormat('',Totaldebit,2,',','.'));
		$("#CRTOTAL").html(numberFormat('',TotalCredit,2,',','.'));
		
		$("#totalDrAmount").attr('value',Totaldebit);
		$("#totalCrAmount").attr('value',TotalCredit);
	}
	</script>