<?php
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IBCIA'. $this->translate(' - IBIZCARE Inventory Accounts'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.8.4.custom.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/default.css') 
						->prependStylesheet($this->basePath() . '/css/lightbox.css') 
						->prependStylesheet($this->basePath() . '/css/fpdf.css')
						->prependStylesheet($this->basePath() . '/css/minimal.css')		
						?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/jquery.ui.datepicker.js')
									  ->prependFile($this->basePath() . '/js/jquery-ui-1.8.4.custom.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/jquery.js')
                                      ->prependFile($this->basePath() . '/js/functions.js') 
									  ->prependFile($this->basePath() . '/js/lightbox.js')
									  ->prependFile($this->basePath() . '/js/minimal.js')
									  ->prependFile($this->basePath() . '/js/pdf.js')
									  ?>
                                      

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><img src="../img/favicon.ico" align="middle" onMouseOut="" onMouseOver="" height="15" width="30" style="vertical-align:middle;" title="IBIZCARE Financial Planning" />&nbsp;<span class="zf-green"><?php echo $this->translate('IBCIA') ?> </span></a>
                    <div class="nav-collapse collapse">
						<?php echo $this->navigation('NavService')->menu()->setUlClass('nav'); ?>
                    </div><!--/.nav-collapse -->
                    <div class="clear"></div>
                    <div class="nav-collapse collapse">
						<?php echo $this->navigation('NavService')->breadcrumbs()->setMinDepth(0)->setMaxDepth(5)->setPartial(array('partial/breadcrumb.phtml', 'Ibcia'));?>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2014 - <?php echo date('Y') ?> by IBIZ Care. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
