<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('IBCIA'. $this->translate(' - IBIZCARE Inventory Accounts'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.8.4.custom.css')
						->prependStylesheet($this->basePath() . '/css/security.css') 
						->prependStylesheet($this->basePath() . '/css/lightbox.css')
						?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/jquery.ui.datepicker.js')
									  ->prependFile($this->basePath() . '/js/jquery-ui-1.8.4.custom.min.js')
									  ->prependFile($this->basePath() . '/js/jquery.js') 
									  ->prependFile($this->basePath() . '/js/lightbox.js')
									  ?>
    </head>
    <body background="../img/home_background.jpg" style="background-repeat:no-repeat;">
        <div class="container">
            <div class="content">
           		<?php echo $this->content; ?>
            </div>
        </div>
        <div class="log-footer">
            Development & Powered by: IBIZCARE, email: <a href="mailto:ibizcare.suprt@gmail.com">ibizcare.suprt@gmail.com</a>
        </div>
        <script language="javascript">
            $(document).ready(function () {
              var bottom = $(window).height()-($('.log-footer').height()+60);
              $('.wrap-security').css('height',bottom);
            });
        </script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>