
<?php if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
?>
<p style="font-family:Tahoma, Geneva, sans-serif;">
<a href="<?php echo $this->url('branch', array('action'=>'add'));?>">Add Branch</a>
</p>
<?php
	$branchTitle = 'Branch Information';
	$this->headTitle($branchTitle);
?>
<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($branchTitle); ?></h1>
<table class="table" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
    <tr>
        <th>Company Name</th>
        <th>Branch Name</th>
        <th>Code</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Fax</th>
        <th>Email</th>
        <th>Web</th>
        <th>&nbsp;</th>
    </tr>
    
    <?php 
		foreach ($branches as $branch) : 
		$class = '';
		if($class == 'evenRow') {
			$class = 'oddRow';
		} else {
			$class = 'evenRow';
		}		
	?>
    <tr class="<?php echo $class; ?>">
        <td><?php echo $this->escapeHtml($branch->COMPANY_NAME);?></td>
        <td><?php echo $this->escapeHtml($branch->BRANCH_NAME);?></td>
        <td><?php echo $this->escapeHtml($branch->BRANCH_CODE);?></td>
        <td><?php echo $this->escapeHtml($branch->ADDRESS);?></td>
        <td><?php echo $this->escapeHtml($branch->PHONE);?></td>
        <td><?php echo $this->escapeHtml($branch->FAX);?></td>
        <td><?php echo $this->escapeHtml($branch->EMAIL);?></td>
        <td><?php echo $this->escapeHtml($branch->WEB);?></td>
        <td>
            <?php
            	if(strtolower($branch->ACTIVE_DEACTIVE) == 'y') {
			?>
            	<a href="<?php echo $this->url('branch',array('action'=>'edit', 'id' => $branch->BRANCH_ID));?>">Edit</a>
            	<a href="#" onclick="getActiveDeactiveBranch(<?php echo $branch->COMPANY_ID;?>,<?php echo $branch->BRANCH_ID;?>,'n')">Deactive</a>
            <?php		
				} else {
			?>
            	<a href="#" onclick="getActiveDeactiveBranch(<?php echo $branch->COMPANY_ID;?>,<?php echo $branch->BRANCH_ID;?>,'y')">Active</a>
            <?php		
				}
			?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<script type="application/javascript">
	function getActiveDeactiveBranch(companyId,branchId,ststus) {
		var alertData	= '';
		
		if(ststus== 'y') {
			alertData = 'active';	
		} else {
			alertData = 'deactive';	
		}
		
		if(!confirm('Are you sure, you want to ' +alertData+' ?')) {
			return false;
		} else {
			var url = '/branch/activeDeactiveBranch?companyId=' +companyId+ '&branchId=' + branchId+ '&ststus=' + ststus;
			$.getJSON(url, function(data) {
			//$.post(url, function(data) {
				if(data==true) {
					window.location.href = "http://ibcia.localhost/branch";
				} else {
					window.location.href = "http://ibcia.localhost/branch";
				}
			});	
		}
	}
</script>