<?php
	$title = 'Delete ORG Type';
	$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
	'<?php echo $this->escapeHtml($retailerInformation->ORG_TYPE)?>'?
</p>
<?php
	$url = $this->url('retailerinformation', array(
		'action'	=> 'delete',
		'id'		=> $retailerInformation->ORG_TYPE_ID,
	));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
    	<input type="hidden" name="id" value="<?php echo (int) $retailerInformation->ORG_TYPE_ID;?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>