<?php if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
?>
<p style="font-family:Tahoma, Geneva, sans-serif;">
	<a href="<?php echo $this->url('retailerinformation', array('action'=>'add'));?>">Add Retailer</a> &nbsp;
</p>
<?php
	$coaTitle = 'Retailer Information';
	$this->headTitle($coaTitle);
?>
<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($coaTitle); ?></h1>
<table class="table" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;">
    <tr>
        <th>SL#</th>
        <!--<th>ZONE</th>-->
        <th>SHOP NAME</th>
        <th>ADDRESS</th>
        <th>PHONE</th>        
        <th>MOBILE</th>
        <th>WEB</th>
        <th>EMAIL</th>
        <!--<th>SR</th>-->
        <th>&nbsp;</th>
    </tr>
    <?php 
	$class = '';
	$i = 1; 
	foreach ($retailerInformations as $retailerInformation) : 
	if($class == 'evenRow') {
		$class = 'oddRow';
	} else {
		$class = 'evenRow';
	}
	?>
    <tr class="<?php echo $class; ?>">
        <td><?php echo $i;?></td>
        <!--<td><?php echo $this->escapeHtml($retailerInformation->NAME);?></td>-->
        <td><?php echo $this->escapeHtml($retailerInformation->SHOP_NAME);?></td>
        <td><?php echo $this->escapeHtml($retailerInformation->ADDRESS);?></td>
        <td><?php echo $this->escapeHtml($retailerInformation->PHONE);?></td>
        <td><?php echo $this->escapeHtml($retailerInformation->MOBILE);?></td>
        <td><?php echo $this->escapeHtml($retailerInformation->WEB);?></td>
        <td><?php echo $this->escapeHtml($retailerInformation->EMAIL);?></td>
        <!--<td><?php echo $this->escapeHtml($retailerInformation->EMPLOYEE_NAME);?></td>-->
        <td>
            <a href="<?php echo $this->url('retailerinformation',array('action'=>'edit', 'id' => $retailerInformation->RETAILER_ID));?>">Edit</a>
            <!-- <a href="<?php //echo $this->url('retailerinformation',array('action'=>'delete', 'id' => $retailerInformation->ORG_TYPE_ID));?>">Delete</a> -->
        </td>
    </tr>
    <?php $i++; endforeach; ?>
</table>
<span style="font-family:Tahoma, Geneva, sans-serif;font-size:85%;">
<?php 
	echo $this->paginationControl($retailerInformations,'sliding',array('partial/paginator.phtml', 'RetailerInformation'),array('route' => 'retailerinformation'));
?>
</span>