<?php
//filename : module/Ibcia/view/ibcia/eod/market-price-file-upload.phtml
$title = 'Market Price File Upload : '.$this->businessdate;
$this->headTitle($title);
?>

<div class='wrap-security'>
	<div class="banner">
		<img src="../img/logo.png" alt="Organization banner" width="288" height="72" title="IBIZCARE Inventory Accounts" />
	</div>
	<div>
        <?php
			$form = $this->form;
			$form->setAttribute('class','security');
			$form->setAttribute('style','width:800px; height:350px; left:35%;');
			$form->setAttribute('action', $this->url('businessdate'));
			$form->prepare();
			 
			echo $this->form()->openTag($form);
		?>
			<h1><?php echo $this->escapeHtml($title); ?></h1>
			<h4 class="error-msg"><?php echo $this->error; ?></h4>
            <table id="holidayTable" style="width:100%;">
                <tr>
                    <td align="center">&nbsp;</td>
                </tr>
                <tr id='loading' style='height:100px; padding:0px; text-align:center; display:none;'>
                    <td align='center' style='height:100px; padding:0px; text-align:center;'>
                        <h4 style='font-weight:normal;margin-top:0px;'>Please, wait while Market Price uploading in process . . .</h4>
                        <span>
                            <img src='../img/preloader2.gif' style='width:40px;' />
                        </span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php 
                            echo $this->formRow($form->get('marketPriceFile'));
                        ?>
                        <sup style="color:red;">*</sup>
                    </td>
                </tr>
                <tr>
                    <td align="center">&nbsp;</td>
                </tr>
                <tr valign='top'>
                    <td style='padding:0px; text-align:left;'>
                        Instruction :<br/>
                        1. File formate [<font style='color:crimson; font-size:85%'>.CSV</font>]<br/>
                        2. Column name &amp; sequence : [<font style='color:crimson; font-size:85%'>BUSINESS_DATE, SYMBOL, OPEN, HIGH, LOW, CLOSE, CHANGE, TRADE, VOLUME, VALUE</font>]<br/>
                        3. Date Formate : [<font style='color:crimson; font-size:85%'>DD-MM-YYYY</font>]
                        
                    </td>
                </tr>
                <tr>
                    <td align="center">&nbsp;</td>
                </tr>
                <tr class="actions">
                    <td align="center">
                        <?php echo $this->formRow($form->get('submit')); ?> &nbsp;
                        <?php echo $this->formRow($form->get('btnBack')); ?> &nbsp;
                        <?php echo $this->formRow($form->get('btnLogout')); ?>
                    </td>
                </tr>
            </table>
			<script language="javascript" type="text/javascript">
                function check() {
					if($("#marketPriceFile").val() == ''){
						alert('Please Upload Market Price File');
						$("#marketPriceFile").focus();
						return false;
					}
					
					if(!confirm('Are you sure, you want to proceed?')) {
                        return false;
                    } else {
						$("#loading").show();
						return true;
					}
                }
            </script>
            
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>