<?php 
	if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	endif;

	$employeeJoiningTitle 	= 'Employee Joining';
	$this->headTitle($employeeJoiningTitle);
	
	$form 	= $this->form;
	$form->setAttribute('action',$this->url('employeejoining'));	
	$form->prepare();
	echo $this->form()->openTag($form);
?>
	<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php echo $this->escapeHtml($employeeJoiningTitle); ?></h1>
    <table class="table" style="font-family:Tahoma, Geneva, sans-serif; font-size:85%;" border="0">
        <tr>
            <th width="5%"><input type='checkbox' name='checkAll' onclick="check('cheque_details')" id='cheque_details_all' value='' disabled="disabled"></th>
            <th width="20%">Name</th>
            <th width="10%">Type</th> 
            <th width="15%">Branch</th>
            <th width="20%">Department</th>
            <th width="20%">Designation</th>
            <th width="10%">Joining Date</th>
        </tr>
        <?php 	$class 			= '';
                $SL				= 1;
                $DATA_FOUND		= 0;
                $FOUND_MESSAGE	= '';
                $FOUND_CLASS	= '';
                $class 			= 'oddRow';
                
                foreach ($investorprofiles as $investorprofile) : // <-- change here! 
                if($class == 'evenRow') {
                    $class = 'oddRow';
                } else {
                    $class = 'evenRow';
                }
                $DATA_FOUND	= 1;
        ?>
            <tr class="<?php echo $class; ?>">
                <td>
                    <input type='checkbox' id='cheque_details<?php echo $SL; ?>' name='EMPLOYEE_ID[]' value='<?php echo $this->escapeHtml($investorprofile->EMPLOYEE_ID); ?>' onclick="check_me('cheque_details');getEnableDisable();"/>
                </td>
                <td><?php echo $this->escapeHtml($investorprofile->EMPLOYEE_NAME);?></td>
                <td><?php echo $this->escapeHtml($investorprofile->EMPLOYEE_TYPE);?></td>
                <td><?php echo $this->escapeHtml($investorprofile->BRANCH_NAME);?></td>
                <td><?php echo $this->escapeHtml($investorprofile->DIVISION_NAME);?></td>     
                <td><?php echo $this->escapeHtml($investorprofile->DESIGNATION);?></td>
                <td>
                    <?php
                    	if($this->escapeHtml($investorprofile->JOINING_DATE)) {
					?>
                    	<input name="JOINING_DATE_<?php echo $this->escapeHtml($investorprofile->EMPLOYEE_ID); ?>" class="FormDateTypeInput" id="JOINING_DATE<?php echo $SL; ?>" type="text" disabled="disabled" onclick="showCalender('JOINING_DATE<?php echo $SL; ?>','JOINING_DATE<?php echo $SL; ?>')" value="<?php echo $this->escapeHtml($investorprofile->JOINING_DATE); ?>"/>
                    <?php			
						} else {
					?>
                    	<input name="JOINING_DATE_<?php echo $this->escapeHtml($investorprofile->EMPLOYEE_ID); ?>" class="FormDateTypeInput" id="JOINING_DATE<?php echo $SL; ?>" type="text" disabled="disabled" onclick="showCalender('JOINING_DATE<?php echo $SL; ?>','JOINING_DATE<?php echo $SL; ?>')"/>
                    <?php		
						}
					?>
                    
                </td>
            </tr>
            <script type="text/javascript">
                $(document).ready(function(){
                    $('#JOINING_DATE'+<?php echo $SL; ?>).datepicker({									
                        dateFormat : 'dd-mm-yy'
                    });
                });
            </script>
        <?php 
            $SL++;
            endforeach;
            if($DATA_FOUND) {
                $FOUND_MESSAGE	= '';
                $FOUND_CLASS	= '';	
            } else {
                $FOUND_MESSAGE	= 'No Data Found.';
                $FOUND_CLASS	= 'error_msg';	
            }  
        ?>
        
        <tr class="<?php echo $class; ?>">
            <td colspan="7" class="<?php echo $FOUND_CLASS; ?>" align="center"><?php echo $FOUND_MESSAGE;?>
            	<?php
					if($DATA_FOUND) {
						echo $this->formSubmit($form->get('submit'));
					}
				?>
            </td>
            <input type='hidden' name='num_of_cheque_details' id='num_of_cheque_details' value='<?php echo $SL; ?>'/>
        </tr>
    </table>

<script type="text/javascript">
	function getEnableDisable() {
		var num_items = document.getElementById('num_of_cheque_details').value;
		
		for(var i=1;i<num_items;i++) {
			if(document.getElementById('cheque_details'+i).checked == true) {
				document.getElementById('JOINING_DATE'+i).disabled = false;
			} else {
				if($("#JOINING_DATE"+i).val() == '') {
					$("#JOINING_DATE"+i).val('');
				}
				document.getElementById('JOINING_DATE'+i).disabled = true;
			}
		}
	}
	
	function doValidationEmployeeJoining() {
		var empchkflag 	= false;
	
		var num_items 	= document.getElementById('num_of_cheque_details').value;
		for(var i=1;i<num_items;i++) {
			if(document.getElementById('cheque_details'+i).checked == true) {
				empchkflag = true;
				
				if($("#JOINING_DATE"+i).val() == '') {
					alert('Please Enter Joining Date!');
					$("#JOINING_DATE"+i).focus();
					return false;
				}
			}
		}
	
		if(empchkflag == false) {
			alert("Please select at least one!");
			return false;
		} else {
			if(!confirm('Are you sure, you want to proceed?')) {
				return false;
			}
			return true;	
		}	
    }
</script>
<?php echo $this->form()->closeTag(); ?>