<?php
	$title = 'Consumption Entry';
	$this->headTitle($title);
	?>
	<h1 style="font-family:Tahoma, Geneva, sans-serif;"><?php 	
	echo $this->escapeHtml($title);
	if(count($flashMessages)) : 
		foreach ($flashMessages as $msg) :
			echo $msg;
		endforeach;
	   endif;
	?></h1>
	<?php
	$form = $this->form;
	$form->setAttribute('action',$this->url('consumptionentry'));
	$form->prepare();	
	echo $this->form()->openTag($form);
	?>
     <table width="100%" border="0" cellspacing="2" cellpadding="5" style="font-family:Tahoma, Geneva, sans-serif;margin:0px auto 0px auto; font-size:75%;">
     	<tr valign="top">
            <td align="left" colspan="2">
             <script type="text/javascript">
					$(document).ready(function() {
					});
					function doValidationPaymentEntry() {
						var formObject = document.consumptionentry;
						var numOfRows = $("#NumberOfRows").val();
						for(var i = 1; i < numOfRows; i++ ) {
							if(document.getElementById('CATEGORY'+i).value !="") {
								if((document.getElementById('QUANTITY'+i).value =="0.00")) {
									alert("Please input quantity/rate!");
									document.getElementById('QUANTITY'+i).focus();
									return false;
								}/*if(document.getElementById('RATE'+i).value=="0.00") {
									alert("Please enter rate!");
									document.getElementById('RATE'+i).focus();
									return false;
								}*/
							}
						}
						/*var netTotalHidden = $('#NETTOTAL_HIDDEN').val().replace(/\,/g,"");	
						var netPayment = $("#NET_PAYMENT").val().replace(/\,/g,"");						
						if(Number(netPayment) > Number(netTotalHidden)){
							var amountMismatch = Number(netTotalHidden - netPayment);
							alert("Net total can not be greater than net payment!\nAmount Mismatch " + amountMismatch.toFixed(2));
							//$("#NET_PAYMENT").attr("value",0.00);
							//$("#NET_PAYMENT").focus();
							return false;
						}*/
						if(!confirm('Are you sure, you want to proceed?')){
								return false;
						}    
						return true;
					}
					function coa_code_suggest(inputString,no) 
					{
						if(inputString.length == 0)
						{
							$('#empIdSuggestions'+no).fadeOut();
						} 
						else 
						{
							$.post('/consumptionentry/getSuggConsumptionProduct',{queryString: inputString, no : no,},
							function(data)
							{
								//alert(data);
								if(data.length >0) 
								{
									$('#suggestingEmpIdList'+no).html(data);
									$('#empIdSuggestions'+no).fadeIn("slow");
									
								}
							});
						}
					}
					function fill_id(thisValue,no,buyPrice,catPriceID,totalSumOfQuantity,coaCode,coaName, unitCalIn) {
					   var coaCodeHeadName = thisValue;
					   if(coaCodeHeadName == '') {
							//document.getElementById('coa_code'+no).value = '';
							document.getElementById('CATEGORY'+no).value = '';
							document.getElementById('CATEGORY_ID'+no).value = '';
							document.getElementById('RATE'+no).value = '';
							document.getElementById('CAT_PRICE_ID'+no).value = ''
							document.getElementById('AQUANTITY'+no).value = '';
							$('#unitCalculationInShow'+no).html('');
							document.getElementById('COA_CODE'+no).value = '';
							document.getElementById('COA_NAME'+no).value = '';
							return false;
						}
						var myArray = coaCodeHeadName.split(','); 
						//document.getElementById('coa_codeshow'+no).innerHTML = myArray[0];
						//document.getElementById('coa_code'+no).value = myArray[0];
						document.getElementById('CATEGORY'+no).value = myArray[1];
						document.getElementById('CATEGORY_ID'+no).value = myArray[0];
						document.getElementById('RATE'+no).value = numberFormat('',buyPrice,2,',','.');
						document.getElementById('CAT_PRICE_ID'+no).value = catPriceID;
						document.getElementById('AQUANTITY'+no).value = totalSumOfQuantity;						
						document.getElementById('COA_CODE'+no).value = coaCode;
						document.getElementById('COA_NAME'+no).value = coaName;
						$('#unitCalculationInShow'+no).html(unitCalIn);
					   $('#empIdSuggestions'+no).fadeOut();
					   
					    //$.post("ajax/JournalDrCrSelect.php", {coaCode: myArray[0]}, 
					   // $.post('/consumptionentry/getJournalDrCrSelect',{coaCode: myArray[1]},	
						//$.getJSON('/consumptionentry/getJournalDrCrSelect',{coaCode: myArray[0]},
						//function(data) {});
					   
					}
					function manufectureProductSugg(inputString,no) 
					{
						if(inputString.length == 0)
						{
							$('#productSuggestions'+no).fadeOut();
						} 
						else 
						{
							$.post('/consumptionentry/getSuggManufecturedProduct',{queryString: inputString, no : no,},
							function(data)
							{
								//alert(data);
								if(data.length >0) 
								{
									$('#suggestingProductList'+no).html(data);
									$('#productSuggestions'+no).fadeIn("slow");
								}
							});
						}
					}
					function fillManufecturedProduct(thisValue,no,salePrice,catPriceID,coaCode,coaName) {
					   var coaCodeHeadName = thisValue;
					   if(coaCodeHeadName == '') {
							document.getElementById('CATEGORY'+no).value = '';
							document.getElementById('CATEGORY_ID'+no).value = '';
							document.getElementById('RATE'+no).value = '';
							document.getElementById('CAT_PRICE_ID'+no).value = ''
							document.getElementById('COA_CODE'+no).value = '';
							document.getElementById('COA_NAME'+no).value = '';
							return false;
						}
						var myArray = coaCodeHeadName.split(',');
						document.getElementById('P_CATEGORY'+no).value = myArray[1];
						document.getElementById('P_CATEGORY_ID'+no).value = myArray[0];
						document.getElementById('P_RATE'+no).value = numberFormat('',salePrice,2,',','.');
						document.getElementById('P_CAT_PRICE_ID'+no).value = catPriceID;
						document.getElementById('P_COA_CODE'+no).value = coaCode;
						document.getElementById('P_COA_NAME'+no).value = coaName;
					   $('#productSuggestions'+no).fadeOut();
					}
					function blankAllFields() {
						for(var i = 1; i<= 10; i++) {
							document.getElementById('CATEGORY'+i).value = '';
							document.getElementById('CATEGORY_ID'+i).value = '';
							//document.getElementById('coa_codeshow'+i).innerHTML = '';
							//document.getElementById('coa_code'+i).value = '';
							//document.getElementById('COATypeD'+i).disabled = false;
							//document.getElementById('COATypeC'+i).disabled = false;
							//document.getElementById('COATypeD'+i).checked = false;
							//document.getElementById('COATypeC'+i).checked = false;
								
						}
						//document.getElementById('particulars').value = '';
						
					}
					
					function AddTabRow() {
						var numOfRows = $("#NumberOfRows").val();
						var numOfRowsId = numOfRows - 1;
						var QUANTITY		= $("#QUANTITY"+numOfRowsId).val();
						QUANTITY			= Number(QUANTITY.replace(/[^\d\.\-\ ]/g, ''));
																
						if(QUANTITY == 0) {
								return false;
						} else {
							//alert('hi there');
							// clone the last row in the table
							var $tr = $("#ClosingBalTab").find("tbody tr:last").clone();
							//$tr = $("#ClosingBalTab").find("tbody tr:last").clone();
							$tr.find("#CATEGORY"+numOfRowsId).attr("name", function()
							{
								// break the field name and it's number into two parts
								var parts = this.name.match(/(\D+)(\d+)$/);
								// create a unique name for the new field by incrementing
								// the number for the previous field by 1
								return parts[1] + ++parts[2];
							// repeat for id attributes
							}).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							}).attr("onKeyup", function(){
								return "coa_code_suggest(this.value,"+numOfRowsId+");";
							}).attr("value", function(){
								return "";
							});
							
							$tr.find("#empIdSuggestions"+numOfRowsId).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							});
							
							$tr.find("#suggestingEmpIdList"+numOfRowsId).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							});
							
							/*$tr.find("#coa_codeshow"+numOfRowsId).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							});*/
							
							$tr.find("#QUANTITY"+numOfRowsId).attr("id", function()
							{
								// break the field name and it's number into two parts
								var parts = this.id.match(/(\D+)(\d+)$/);
								// create a unique name for the new field by incrementing
								// the number for the previous field by 1
								return parts[1] + ++parts[2];
							// repeat for id attributes
							}).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							}).attr("onKeyup", function(){
								//return "removeChar(this.value);";
							}).attr("onfocus", function(){
								if(this.value=="0.00") this.value="";
							}).attr("onblur", function(){
								numberFormat("QUANTITY"+numOfRowsId,this.value,'2',',','.'); if((this.value=="") || (this.value=='0')) this.value="0.00";calculateTotal(this.id,this.value,numOfRowsId);
							}).attr("value", function(){
								return "";
							});
							
							
							$tr.find("#RATE"+numOfRowsId).attr("id", function()
							{
								// break the field name and it's number into two parts
								var parts = this.id.match(/(\D+)(\d+)$/);
								// create a unique name for the new field by incrementing
								// the number for the previous field by 1
								return parts[1] + ++parts[2];
							// repeat for id attributes
							}).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							}).attr("onKeyup", function(){
								return "removeChar(this);calculateTotal(this.id,this.value,"+numOfRows+");";
							}).attr("value", function(){
								return "";
							});
							
							/*$tr.find("#COATypeC"+numOfRowsId).attr("name", function()
							{
								// break the field name and it's number into two parts
								var parts = this.name.match(/(\D+)(\d+)$/);
								// create a unique name for the new field by incrementing
								// the number for the previous field by 1
								return parts[1] + ++parts[2];
							// repeat for id attributes
							}).attr("id", function(){
								var parts = this.id.match(/(\D+)(\d+)$/);
								return parts[1] + ++parts[2];
							}).attr("onClick", function(){
								return "DrCrAmountAlign("+numOfRows+"); totalDRCRShow();";
							}).attr("checked", function(){
								return false;
							});*/
							
							
							
							$("#ClosingBalTab").find("tbody tr:last").after($tr);							
							//$("#coa_codeshow"+numOfRows).html('');
							$("#NumberOfRows").attr("value",Number(numOfRows)+1);
						}
					}
					
					function totalDRCRShow() {
						var numOfRows = $("#NumberOfRows").val();
						var k=0;
						var i=0;
						var Totaldebit = 0;
						var TotalAmount = 0.00;
						var TotalQty = 0.00;
						var TotalDiscount = 0.00;
						for(i = 1; i < numOfRows; i++){
							if((document.getElementById('QUANTITY'+i).value !="0.00") || (document.getElementById('RATE'+i).value !="0.00")) {
							  if((document.getElementById('TOTAL_AMOUNT'+i).value !="0.00")){
								  var totalAmount = document.getElementById('TOTAL_AMOUNT'+i).value;
								  totalAmount     = totalAmount.replace(/\,/g,"");
								  totalAmount     = Number(totalAmount);
								  TotalAmount      = TotalAmount + totalAmount;
							  }								
							}
						}
						$("#NET_PAYMENT").attr("value",numberFormat('',TotalAmount,2,',','.'));
					}
					function manufecturedNetTotalShow() {
						var numOfRows = $("#ManufecturedNumberOfRows").val();
						var k=0;
						var i=0;
						var Totaldebit = 0;
						var TotalAmount = 0.00;
						var TotalQty = 0.00;
						var TotalDiscount = 0.00;
						for(i = 1; i < numOfRows; i++){
							if((document.getElementById('P_QUANTITY'+i).value !="0.00") || (document.getElementById('P_RATE'+i).value !="0.00")) {
							  if((document.getElementById('P_TOTAL_AMOUNT'+i).value !="0.00")){
								  var totalAmount = document.getElementById('P_TOTAL_AMOUNT'+i).value;
								  totalAmount     = totalAmount.replace(/\,/g,"");
								  totalAmount     = Number(totalAmount);
								  TotalAmount      = TotalAmount + totalAmount;
							  }								
							}
						}
						$("#P_NET_PAYMENT").attr("value",numberFormat('',TotalAmount,2,',','.'));
						$("#isProduction").attr("value",'yes');
					}
					function pageReset() {
						$('#viewBalanceSheet').fadeOut("slow");
						$('#preloader').fadeIn("slow");
						//$('#viewPTBStatement').fadeOut("slow");
						$('#noDataFound').fadeIn('slow');
					}
					function calculateTotal(id,value,counter){
						var total = 0.00;
						var netTotal = 0.00;
						var avgRate = 0.00;
						var actualDiscount = 0.00;
						if(id=='QUANTITY'+counter){
							var rate = $("#RATE"+counter).val().replace(/\,/g,"");
							var quantity = $("#QUANTITY"+counter).val().replace(/\,/g,"");
							rate  = Number(rate);
							value = value.replace(/\,/g,"");
							total = Number(value * rate);
							$("#TOTAL_AMOUNT"+counter).attr("value",total.toFixed(2));	
							//alert(total);
							totalDRCRShow();
						}	
					}
					function calManufecturedProductTotal(id,value,counter){
						var total = 0.00;
						var netTotal = 0.00;
						var avgRate = 0.00;
						var actualDiscount = 0.00;
						if(id=='P_QUANTITY'+counter){
							var rate = $("#P_RATE"+counter).val().replace(/\,/g,"");
							var quantity = $("#P_QUANTITY"+counter).val().replace(/\,/g,"");
							rate  = Number(rate);
							value = value.replace(/\,/g,"");
							total = Number(value * rate);
							$("#P_TOTAL_AMOUNT"+counter).attr("value",total.toFixed(2));	
							//alert(total);
							manufecturedNetTotalShow();
						}else if(id=='P_RATE'+counter){
							//alert(value);
							var quantity = $("#P_QUANTITY"+counter).val().replace(/\,/g,"");
							quantity = Number(quantity);
							value = Number(value.replace(/\,/g,""));
							total = Number(value) * Number(quantity);
							$("#P_TOTAL_AMOUNT"+counter).attr("value",total.toFixed(2));
							manufecturedNetTotalShow();
						}	
					}
					function getSuppCOACode(suppID,no) {
						//$.post('/consumptionentry/getSuppCOACode',{suppID: suppID}, function(data) {
						$.getJSON('/consumptionentry/getSuppCOACode',{suppID: suppID}, function(data) {
							//alert(data);
							if(data.length >0) 
							{
								for (var i = 0; i < data.length; i++) {
									$('#PAYABLE_COA'+no).attr("value",data[i].payableCoa);
									$('#PAYABLE_COA_NAME'+no).attr("value",data[i].payableCoaName);
									$('#SUPP_SHORT_NAME'+no).attr("value",data[i].suppShortName);
								}
								
							} else {
								$('#PAYABLE_COA'+no).attr("value",'');
								$('#PAYABLE_COA_NAME'+no).attr("value",'');
								$('#SUPP_SHORT_NAME'+no).attr("value",'');
							}
						});
					}
					function placeAmountInHidden(discountValue,no){
						$('#INDVDISCOUNTHIDDEN'+no).attr("value",discountValue);
					}
                </script>
            </td>
        </tr>
        <tr valign="top">
            <td align="left" width="50%">
               <fieldset style='width:95%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
					<legend style='border:0px;'>Inventory Use</legend>
                            <table border="0" cellpadding="2" cellspacing="2" width="100%" style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;">
                                <tr>
                                    <td colspan="5">
                                    	<table id="" border="0" width="50%" align="center" cellspacing="1" cellpadding="3" style="font-size:75%;font-family:Tahoma, Geneva, sans-serif;">
										   <?php 
                                            $tableTR = '';
                                            $tableTR .='<tr valign="top" style="font-weight:bold; text-align:center; background:#E8E1E1;">
                                                            <td width="25%" align="center" style="padding-right:10px;">PRODUCT</td>
															<td width="10%" align="right" style="padding-right:10px;">AVAILABLE QTY</td>
                                                            <td width="10%" align="right" style="padding-right:10px;">QTY</td>
															<td width="10%" align="center" style="padding-right:10px;">UNIT MEASUREMENT</td>
                                                            <td width="10%" align="right" style="padding-right:10px;">RATE</td>
                                                            <td width="15%" align="right" style="padding-right:10px;">TOTAL</td>											
                                                        </tr>';
                                            $class = 'evenRow';
                                            for($i=1; $i<=10; $i++){
                                            if($class == 'evenRow') {
                                                $class = 'oddRow';
                                            } else {
                                                $class = 'evenRow';
                                            }
                                            $j = $i-1;
                                            $tableTR .="<tr valign='top' class='".$class."'>
                                                            <td  align='left' class=''>
                                                                 <div style='position:relative;'>
                                                                    <input name='CATEGORY{$i}' type='text'  id='CATEGORY{$i}'  style='width:120px;font-family:Tahoma, Geneva, sans-serif;' value='' autocomplete='off' onkeyup='coa_code_suggest(this.value,{$i});' />
                                                                    <input name='CATEGORY_ID{$i}' type='hidden'  id='CATEGORY_ID{$i}' value='' />
                                                                    <input name='COA_CODE{$i}' type='hidden'  id='COA_CODE{$i}' value='' />
                                                                    <input name='COA_NAME{$i}' type='hidden'  id='COA_NAME{$i}' value='' />
                                                                    <div id='empIdSuggestions{$i}' style='display:none;width:120px; height:250px;' class='ClassempIdSuggestions'>
                                                                        <div id='suggestingEmpIdList{$i}' class='ClasssuggestingEmpIdList'>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </td>
															<td  align='left'>
																 <input type='text' name='AQUANTITY{$i}' id='AQUANTITY{$i}' class='FormNumericTypeInput' style='width:50px;' value=\"0\" maxlength='10' autocomplete='off' readonly='readonly'/>
															</td>
                                                            <td  align='left'>
                                                                 <input type='text' name='QUANTITY{$i}' id='QUANTITY{$i}' onkeyup='removeChar(this);' class='FormNumericTypeInput' style='width:50px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"QUANTITY{$i}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\";calculateTotal(this.id,this.value,{$i});' value=\"0.00\" maxlength='10' autocomplete='off'/>
                                                            </td>
															<td  align='center'>
                                                                 <span id='unitCalculationInShow{$i}'>#</span>
                                                            </td>
                                                            <td  align='left' class='FormSelectTypeInput'>
                                                                 <input type='hidden' name='CAT_PRICE_ID{$i}' id='CAT_PRICE_ID{$i}' value=''/>
                                                                 <input type='text' name='RATE{$i}' id='RATE{$i}' onkeyup='removeChar(this);calculateTotal(this.id,this.value,{$i});' class='FormNumericTypeInput' style='width:50px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"RATE{$i}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\";calculateTotal(this.id,this.value,{$i});' value=\"0.00\" maxlength='10' autocomplete='off' readonly='readonly'/>
                                                            </td>
                                                            <td  align='left' class='FormSelectTypeInput'>
                                                                 <input type='text' name='TOTAL_AMOUNT{$i}' id='TOTAL_AMOUNT{$i}' onkeyup='removeChar(this);' class='FormNumericTypeInput' style='width:100px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"TOTAL_AMOUNT{$i}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\"; ' value=\"0.00\" maxlength='15' readonly='readonly' autocomplete='off'/>
                                                            </td>
                                                        </tr>";		
                                            }
                                            echo $tableTR;
                                           ?>
                                            <tr valign='top' style="font-weight:bold;">
                                                <td colspan='5'  align='right' class=''>Net Total</td>
                                                <td align='right' style="padding-right:10px;"><input type="text" name="NET_PAYMENT" id="NET_PAYMENT" onkeyup="removeChar(this);" class="FormNumericTypeInput" style="width:100px;" onblur="numberFormat('NET_PAYMENT',this.value,2,',','.'); if((this.value=='') || (this.value==0)) this.value='0.00';" value="0.00" maxlength="20" autocomplete="off" onfocus="if(this.value=='0.00') this.value='';"
                                                /></td>
                                            </tr>
                                       </table>
                                    </td>
                                </tr>
                            </table>
                </fieldset>
            </td>
            <td align="left" width="50%">
                <fieldset style='width:95%;border:0px;border-top:1px solid #2b2d93;font-family:Tahoma, Geneva, sans-serif;'>
					<legend style='border:0px;'>Production</legend>
                            <table border="0" cellpadding="2" cellspacing="2" width="100%" style="font-family:Tahoma, Geneva, sans-serif; font-size:100%;">
                                <tr>
                                    <td colspan="4">
                                    	<table id="" border="0" width="50%" align="center" cellspacing="1" cellpadding="3" style="font-size:75%;font-family:Tahoma, Geneva, sans-serif;">
										   <?php 
                                            $tableTR = '';
                                            $tableTR .='<tr valign="top" style="font-weight:bold; text-align:center; background:#E8E1E1;">
                                                            <td width="25%" align="center" style="padding-right:10px;">PRODUCT</td>
                                                            <td width="10%" align="right" style="padding-right:10px;">QTY</td>
                                                            <td width="10%" align="right" style="padding-right:10px;">RATE</td>
                                                            <td width="15%" align="right" style="padding-right:10px;">TOTAL</td>											
                                                        </tr>';
                                            $class = 'evenRow';
                                            for($k=1; $k<=10; $k++){
                                            if($class == 'evenRow') {
                                                $class = 'oddRow';
                                            } else {
                                                $class = 'evenRow';
                                            }
                                            $l = $k-1;
                                            $tableTR .="<tr valign='top' class='".$class."'>
                                                            <td  align='left' class=''>
                                                                 <div style='position:relative;'>
                                                                    <input name='P_CATEGORY{$k}' type='text'  id='P_CATEGORY{$k}'  style='width:150px;font-family:Tahoma, Geneva, sans-serif;' value='' autocomplete='off' onkeyup='manufectureProductSugg(this.value,{$k});' />
                                                                    <input name='P_CATEGORY_ID{$k}' type='hidden'  id='P_CATEGORY_ID{$k}' value='' />
                                                                    <input name='P_COA_CODE{$k}' type='hidden'  id='P_COA_CODE{$k}' value='' />
                                                                    <input name='P_COA_NAME{$k}' type='hidden'  id='P_COA_NAME{$k}' value='' />
                                                                    <div id='productSuggestions{$k}' style='display:none;width:150px; height:250px;' class='ClassempIdSuggestions'>
                                                                        <div id='suggestingProductList{$k}' class='ClasssuggestingEmpIdList'>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td  align='left'>
                                                                 <input type='text' name='P_QUANTITY{$k}' id='P_QUANTITY{$k}' onkeyup='removeChar(this);' class='FormNumericTypeInput' style='width:60px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"P_QUANTITY{$k}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\";calManufecturedProductTotal(this.id,this.value,{$k});' value=\"0.00\" maxlength='10' autocomplete='off'/>
                                                            </td>
                                                            <td  align='left' class='FormSelectTypeInput'>
                                                                 <input type='hidden' name='P_CAT_PRICE_ID{$k}' id='P_CAT_PRICE_ID{$k}' value=''/>
                                                                 <input type='text' name='P_RATE{$k}' id='P_RATE{$k}' onkeyup='removeChar(this);calculateTotal_p(this.id,this.value,{$k});' class='FormNumericTypeInput' style='width:60px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"P_RATE{$k}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\";calManufecturedProductTotal(this.id,this.value,{$k});' value=\"0.00\" maxlength='10' autocomplete='off'/>
                                                            </td>
                                                            <td align='left' class='FormSelectTypeInput'>
                                                                 <input type='text' name='P_TOTAL_AMOUNT{$k}' id='P_TOTAL_AMOUNT{$k}' onkeyup='removeChar(this);' class='FormNumericTypeInput' style='width:100px;' onfocus='if(this.value==\"0.00\") this.value=\"\";' onblur='numberFormat(\"P_TOTAL_AMOUNT{$k}\",this.value,2,\",\",\".\"); if((this.value==\"\") || (this.value==0)) this.value=\"0.00\";' value=\"0.00\" maxlength='15' readonly='readonly' autocomplete='off'/>
                                                            </td>
                                                        </tr>";		
                                            }
                                            echo $tableTR;
                                           ?>
                                            <tr valign='top' style="font-weight:bold;">
                                                <td colspan='3'  align='right' class=''>Net Total</td>
                                                <td align='right' style="padding-right:10px;"><input type="text" name="P_NET_PAYMENT" id="P_NET_PAYMENT" onkeyup="removeChar(this);" class="FormNumericTypeInput" style="width:100px;" onblur="numberFormat('P_NET_PAYMENT',this.value,2,',','.'); if((this.value=='') || (this.value==0)) this.value='0.00';" value="0.00" maxlength="20" autocomplete="off" onfocus="if(this.value=='0.00') this.value='';"
                                                /></td>
                                            </tr>
                                       </table>
                                    </td>
                                </tr>
                            </table>
                </fieldset>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
            				 <input type="hidden" name="NumberOfRows" id="NumberOfRows" value="<?php echo $i; ?>"/>
                             <input type="hidden" name="ManufecturedNumberOfRows" id="ManufecturedNumberOfRows" value="<?php echo $k; ?>"/>
                             <input type="hidden" name="isProduction" id="isProduction" value="no"/>
							 <?php echo $this->formRow($form->get('CONSUMPTION_NO')); ?>
                             <input style="font-family:Tahoma, Geneva, sans-serif; font-size:120%;" type="submit" name="insertJournal" id="insertJournal" value="Submit" />
                             <input style="font-family:Tahoma, Geneva, sans-serif; font-size:120%;" type="reset" name="reset" id="reset" value="Reset" />
            </td>
        </tr>
    </table>
     
	<?php 
	//echo $this->formCollection($form);
	echo $this->form()->closeTag();
	?>